### ISSUE TITLE
Support t816, t416

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#10]
There are a few subtle differences between the t1616/3216 and t416/816. We need to account for these. At present it's not clear to me whether this can be done with the same variants files or whether a new variant is needed. But it looks like it may just work? I don't see TCB being used for anything?

**Comment by freemovers** [comment]
TCB is used for millis, but it is defined with the extra flags in the boards.txt:
`at1616.build.extra_flags=-DMILLIS_USE_TIMERB1 -DNO_EXTERNAL_I2C_PULLUP`
Could make that part of a menu option, or move the millis to TCB0 in general.

**Comment by SpenceKonde** [comment]
Moved millis to timerB0. 

We needed to do that anyway because tone() uses timerB1 so tone() would hose millis() if it used timerB1.
