### ISSUE TITLE
Link to board manager URL's is broken

### ISSUE THREAD

**Issue by rsoric** [SpenceKonde/megaTinyCore#1001]
Hi @SpenceKonde,

the link for the board manager URL for Arduino (http://drazzy.com/package_drazzy.com_index.json) is broken. The host domain refuses to connect. 

This is reported by Arduino IDE upon startup. I assume that just manual installation is supported for now, but just letting you know.

**Comment by SpenceKonde** [comment]
It is working now, but only for http, still not https. I cannot seem to get it to serve https as https.

**Comment by rsoric** [comment]
Great, thanks!
