### ISSUE TITLE
Arduino IDE 2.2.1 Board Manager Fails to Add

### ISSUE THREAD

**Issue by JasXSL** [SpenceKonde/megaTinyCore#1005]
Installing via the board manager URL in IDE 2.2.1 causes the following error:

`2023-09-22T22:37:18.467Z root ERROR Detected an error response during the gRPC core client initialization: code: 9, message: Loading index file: loading json index file c:\Users\<user>\AppData\Local\Arduino15\package_drazzy.com_index.json: open c:\Users\<user>\AppData\Local\Arduino15\package_drazzy.com_index.json: The system cannot find the file specified.`

A file called `package_drazzy.json` is created in Arduino15 instead. Manually renaming it to `package_drazzy.com_index.json` makes it show up.

**Comment by SpenceKonde** [comment]
This sounds like a regression in the Arduino IDE. The file is named in the format they suggested, and works in earlier versions. It's also impacting the CI because the CI uses the latest CLI version, which is where the bug appears to be.
