### ISSUE TITLE
Missing files / incorrect URL in V2.6.9

### ISSUE THREAD

**Issue by pcfreak1201** [SpenceKonde/megaTinyCore#1017]
As in Discussion https://github.com/SpenceKonde/megaTinyCore/discussions/1016
I've got the error on 
`avr-gcc-7.3.0-atmel3.6.1-azduino7b-x86_64-pc-linux-gnu.tar.bz2`
so looks like the release script or the destinations are wrong?!

**Comment by SpenceKonde** [comment]
Oh, right, I hadn't uploaded the windows version, because I was looking at compression algorithms and being annoyed that arduino won't open lzma2 archives, because those compress faster and result in a file 1/3rd the size.

Should be good now.

**Comment by pcfreak1201** [comment]
Nope, the linux files from DXCore are still not present.
