### ISSUE TITLE
Problem with library after new update.

### ISSUE THREAD

**Issue by saysphilippe** [SpenceKonde/megaTinyCore#102]
Hi! In Arduino IDE it's an update for the board library and when trying to download it it fails with a CRC check. And none of the versions will now work. Big problem in little China. 
![image](https://user-images.githubusercontent.com/49074171/67494596-bcc4ca80-f679-11e9-9c27-db8eeef82fa9.png)

**Comment by SpenceKonde** [comment]
Argh, I broke something with the 1.0.6 release it looks like. I will try to
figure out how to fix it.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by saysphilippe** [comment]
Thanks man! Btw: I love your work!

**Comment by SpenceKonde** [comment]
I think I've fixed this in the github repo; can you check if replacing the board manager script with this works now? (I don't seem to have the cert I need to log into my webserver to update it there currently). You may have to manually clear out the arduino15 folder though (on windows this is in C:/Users/(your username)/AppData (hidden folder)/Local/Arduino15 to get rid of the broken installation. 
https://raw.githubusercontent.com/SpenceKonde/ReleaseScripts/master/package_drazzy.com_index.json

**Comment by SpenceKonde** [comment]
This fix has been verified and is now in the json file in the normal location.

**Comment by SpenceKonde** [comment]
Somehow, the tool I had used to calculate the SHA-256 hash used to verify that the download isn't corrupt gave me a totally bogus result.
