### ISSUE TITLE
Gank @MCUdude's Logic library (per #98)

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#103]
Hans wrote a lovely library called Logic for his MegaCoreX, which he says is fully compatible with the 0-series and 1-series tinies. We should steal it and add to megaTinyCore

**Comment by MCUdude** [comment]
Please do! Just remember to credit @tgtakaoka as well. He was the one the ported it over to the tiny0/tiny1's 🥇

**Comment by SpenceKonde** [comment]
@MCUdude - is the version of Logic in MegaCoreX master branch the correct one to use (the one that has the tiny0/tiny1 support?

**Comment by SpenceKonde** [comment]
Okay, yup, that version of Logic supports ATtiny parts!

@tgtakaoka - do you want credit as tgtakaoka, or Tadashi G. Takaoka ?

**Comment by MCUdude** [comment]
Latest version is in the master branch, yes.
