### ISSUE TITLE
Typo in boards.txt

### ISSUE THREAD

**Issue by ruthsarian** [SpenceKonde/megaTinyCore#1048]
line 955 of boards.txt

`atxy6.menu.bodmode.sampledlow.bootloader.bodmodebits=11010`

should be

`atxy6.menu.bodmode.sampledslow.bootloader.bodmodebits=11010`

The missing 's' in sampledslow means the sampled/sampled (125 Hz) BOD mode will not work when selected in the Arduino IDE.

**Comment by SpenceKonde** [comment]
Corrected, along with several other issues.
