### ISSUE TITLE
Is missing: Tools -> UART for Bootloader = TX:9 (PB2), RX:8 (PB3) 

### ISSUE THREAD

**Issue by avandalen** [SpenceKonde/megaTinyCore#1074]
Hi Spence,
If this board is selected:
Board = megaTinyCore > Attiny3217/3217…
Then this tool setting is missing:
Tools -> UART for Bootloader = TX:9 (PB2), RX:8 (PB3)

(It is still visible if this board is selected: Board = megaTinyCore > Attiny3217 w/Optiboot)

**Comment by hmeijdam** [comment]
That's to select which UART bootloader you want when you do "burn bootloader". You select an option without a bootloader, so nothing to select.
