### ISSUE TITLE
Upload sketch with SerialUPDI HV Programmer doesn't work

### ISSUE THREAD

**Issue by avandalen** [SpenceKonde/megaTinyCore#1076]
Hi,
I'm working on a new description of how to burn the bootloader:
https://avdweb.nl/arduino/attiny3217/bootloader-attiny3217

I have a problem with the megaTinyCore version 2.6.10 and the SerialUPDI_HV_Programmer

The used SerialUPDI HV Programmer is this:
https://github.com/wagiminator/AVR-Programmer/tree/master/SerialUPDI_HV_Programmer

This works well: I can upload sketches with the SerialUPDI HV programmer, with the high voltage pulse disabled to an new and unused ATtiny3217.

Problem:
Uploading sketches with the 12V pulse enabled, gives an error message, see below.

Can you try to upload a sketch to a new and unused ATtiny3217 with the 12V HV puls enabled?

Maybe it is necessary to first burn the bootloader (UPDI=UPDI, not reset pin) before being able to upload a sketch with HV pulse? The bootloader is maybe just needed to configures some fuses?

Note that, in the year 2020, I had successfully worked with the megaTinyCore and I was able to upload sketches via UPDI and also via the burned bootloader.

Arduino settings:
![Arduino settings](https://github.com/wagiminator/AVR-Programmer/assets/1129648/435fc836-bd43-411a-b462-83a2c5d407ed)

Scope
![UPDI with HV](https://github.com/wagiminator/AVR-Programmer/assets/1129648/d0e0a2a3-d511-4f39-8ae8-fe1363a950c9)

Error messages
[without HV pulse OK.txt](https://github.com/wagiminator/AVR-Programmer/files/14731976/without.HV.pulse.OK.txt)

[with HV12V pulse NOT OK.txt](https://github.com/wagiminator/AVR-Programmer/files/14731977/with.HV12V.pulse.NOT.OK.txt)

**Comment by pcfreak1201** [comment]
May be the timing is too tight between pulse and prog?
https://onlinedocs.microchip.com/oxy/GUID-A2109DC3-B5FF-4E1B-BDB5-622C21D35F43-en-US-5/GUID-93D88655-0A9C-4923-A03F-077491438F6F.html

**Comment by avandalen** [comment]
Maybe, but I cant do anything about it, it is controlled by the megaTinyCore and the Arduino IDE.

**Comment by avandalen** [comment]
I closed this issue because the actual problem was this:
https://github.com/SpenceKonde/AVR-Guidance/issues/20
