### ISSUE TITLE
Alternate USART port pins setting for ATTiny816 doesn't work

### ISSUE THREAD

**Issue by EclipseBoom** [SpenceKonde/megaTinyCore#108]
Tested with Tools->UART Pins TX:14, RX:15  on ATTiny816 using latest core manually installed.

Does not produce output.  Also PORTMUX.CTRLB bit 0 does not change to 1

If I manually set the RX and TX PinMode and then set PORTMUX.CTRLB = 0x01 it works

**Comment by SpenceKonde** [comment]
Thanks. For some reason I only had the code in for xy2 parts.

**Comment by EclipseBoom** [comment]
Thanks for the quick response.  Will test now.

BTW the Nano->UPDI programmer works well for 816 and 402 parts that I have tested so far.
