### ISSUE TITLE
Error while burning bootloader.

### ISSUE THREAD

**Issue by hoka83** [SpenceKonde/megaTinyCore#1089]
have anyone faced this error before,
i am just connectin arduino uno as a programmer for AVR128DA chip using updi and it gives me this error:
avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description
avrdude: jtagmkII_program_enable(): bad response to enter progmode command: RSP_ILLEGAL_MCU_STATE
avrdude: jtagmkII_program_enable(): bad response to enter progmode command: RSP_ILLEGAL_MCU_STATE
avrdude: jtagmkII_read_byte(): bad response to read memory command: RSP_ILLEGAL_MCU_STATE
avr_read(): error reading address 0x0000
read operation not supported for memory "signature"
avrdude: error reading signature data for part "AVR128DA28", rc=-2
avrdude: error reading signature data, rc=-2
avrdude: jtagmkII_program_disable(): bad response to leave progmode command: RSP_ILLEGAL_MCU_STATE
Error while burning bootloader.

![IMG_6060](https://github.com/SpenceKonde/megaTinyCore/assets/105120867/198d852a-0d68-44df-8db9-8e70e0d53e04)

 
![IMG_6061 (1)](https://github.com/SpenceKonde/megaTinyCore/assets/105120867/1fdbca09-50a1-40d4-8619-19a6f63c7773)

![hardware connection](https://github.com/SpenceKonde/megaTinyCore/assets/105120867/0cdf9d89-15d1-4e8e-a3f7-5af5cfc9149e)

**Comment by SpenceKonde** [comment]
Per elsewhere in documentation I no longer offer support for jtag2updi because I coudlnt't solve that problem after months of work
