### ISSUE TITLE
 error message when downloading the board JSON file

### ISSUE THREAD

**Issue by BroekerFrank** [SpenceKonde/megaTinyCore#1126]
I get an error message when downloading the board JSON file.
This means that the JSON file cannot be loaded.
I am using the Arduino IDE V1.8.19.
This error has been occurring for a few days. I suspect the JSON file is not formatted correctly or the Arduino check is too strict.
Error message:
<Error downloading from http://drazzy.com/package_drazzy.com_index.json>

I have already reported this error some time ago. Unfortunately, the error is now occurring again.

Greetings
Frank

**Comment by moose4lord** [comment]
This is an ongoing problem with the security certificate for Mr Konde's web site. See issue #1117 for a workaround.

**Comment by SpenceKonde** [comment]
Duplicate closed. I go away for any length of time, and the fucking certs go bad no matter how many instructions for autorenew I set up.

**Comment by hmeijdam** [comment]
> I go away for any length of time.
Good to see you back here.
