### ISSUE TITLE
Typo in core_parameters.h (no idea about consequences)

### ISSUE THREAD

**Issue by Teuxe** [SpenceKonde/megaTinyCore#1131]
megaavr/cores/megatinycore/core_parameters.h:13
defined(ATTIYNCORE)
should probably be
defined(ATTINYCORE)

**Comment by SpenceKonde** [comment]
Yeah probly. I'll do that soon as I get a computer set up with GitHub and basic amenities,

**Comment by SpenceKonde** [comment]
No, sorry, the AVRrc (Reduced Core) chips like that are outside of the scope of megaTinyCore and are ill suited to arduino-like usage.
