### ISSUE TITLE
detachInterrupt broke PINxCTRL Pullup

### ISSUE THREAD

**Issue by PM04290** [SpenceKonde/megaTinyCore#1143]
using detachInterrupt broke previous pinMode(pin, INPUT_PULLUP) by putting 0x07 mask on PINxCTRL register.

**Comment by SpenceKonde** [comment]
Thanks. Actually, what it was doing was bitwise anding it with 0xF1, instead of 0xF8 (=~0x07). Thus it is failing to clear the interrupt sense configuration's low bit in addition to trashing the pullup setting. So half of the options won't actually properly turn off either)

**Comment by SpenceKonde** [comment]
c03d4a592aab37f071abebde3849a1126dfc856c fixes this issue
