### ISSUE TITLE
analogWrite does not work on PA3 - ATtiny1614

### ISSUE THREAD

**Issue by Merlin04** [SpenceKonde/megaTinyCore#115]
`analogWrite` doesn't work on PA3 on my ATtiny1614. All it does is either go high or low, depending if the value is above or below a threshold. I'm not entirely sure why, but when looking around I found this in `megaavr/variants/txy4/pins_arduino.h`:
```c++
const uint8_t PROGMEM digital_pin_to_timer[] = {
  	// Left side, top to bottom
	TIMERA0, 		// 0  PA4
	TIMERA0, 		// 1  PA5	
	#ifdef DAC0
    DACOUT, // 2  PA6
	#else
	NOT_ON_TIMER, // 2  PA6
	#endif
	NOT_ON_TIMER, 	// 3  PA7
	NOT_ON_TIMER, 	// 4  PB3
	TIMERA0, 		// 5  PB2
	// Right side, bottom to top
	TIMERA0, 		// 6  PB1
	TIMERA0, 		// 7  PB0
	//skip PA0 UPDI
	NOT_ON_TIMER, 	// 8  PA1
	TIMERA0, 		// 9  PA2
	NOT_ON_TIMER,  	// 10 PA3
	NOT_ON_TIMER  	// 11 PA3
  
  
};
```
It looks like PA2 is `TIMERA0` even though it is not a PWM pin, but PA3 is `NOT_ON_TIMER`. Could this be why?

**Comment by SpenceKonde** [comment]
Your diagnosis is accurate. I've checked in a fix - alas this was not - quite - in time for 1,1,1 - though I'll do another release before the end of the month
