### ISSUE TITLE
Core_Device.h wrong definition for some items on some #define lines (minor bug)

### ISSUE THREAD

**Issue by LaurentR59** [SpenceKonde/megaTinyCore#1153]
Hi

Just put a look on Tiny X16:.

The lines with Tiny 416 looks like OK but for others CPU x16 need some update:

the lines
 #define __AVR_ATtinyx06__ 
should be replaced by:

  #define __AVR_ATtinyx16__

Is'n it?

Regards
Laurent

Present version:

...
#elif defined(__AVR_ATtiny3216__)
  #define MEGATINYCORE_MCU 3216
  #define MEGATINYCORE_SERIES 1
  #define __AVR_ATtinyx06__
  #define __AVR_ATtinyxy6__
  #define _AVR_FLASH 32
#elif defined(__AVR_ATtiny1616__)
  #define MEGATINYCORE_MCU 1616
  #define MEGATINYCORE_SERIES 1
  #define __AVR_ATtinyx06__
  #define __AVR_ATtinyxy6__
  #define _AVR_FLASH 16
#elif defined(__AVR_ATtiny816__)
  #define MEGATINYCORE_MCU 816
  #define MEGATINYCORE_SERIES 1
  #define __AVR_ATtinyx06__
  #define __AVR_ATtinyxy6__
  #define _AVR_FLASH 8
#elif defined(__AVR_ATtiny416__)
  #define MEGATINYCORE_MCU 416
  #define MEGATINYCORE_SERIES 1
  #define __AVR_ATtinyx16__
  #define __AVR_ATtinyxy6__
  #define _AVR_FLASH 4

**Comment by SpenceKonde** [comment]
Thanks will look into this
