### ISSUE TITLE
Enhancement request: Use internal DAC as input for Analog Comparator

### ISSUE THREAD

**Issue by ArnieO** [SpenceKonde/megaTinyCore#1156]
According to datasheet it should be possible to route internal ADC to the negative input of the Analog Comparator. This feature seems to not be implemented (yet?) in megaTinyCore?

I started this as a Discussion (https://github.com/SpenceKonde/megaTinyCore/discussions/1155), but after having tried to set the MUX "manually", I fail to make it work as expected. See more extensive description and input in https://github.com/SpenceKonde/megaTinyCore/discussions/1155#discussioncomment-11049215

**Comment by SpenceKonde** [comment]
This absolutely should work!!!!

Please post simplest demo code and a schematic (hand drawn schematic on a cocktail napkin is preferable to anything made with fritzing) that demonstrates this, because I'm sure I've done this multiple times without issues.....

**Comment by ArnieO** [comment]
> This absolutely should work!!!!
> 
> Please post simplest demo code and a schematic (hand drawn schematic on a cocktail napkin is preferable to anything made with fritzing) that demonstrates this, because I'm sure I've done this multiple times without issues.....

This sounds promising! 

Maybe I misunderstand [the documentation](https://github.com/SpenceKonde/megaTinyCore/tree/master/megaavr/libraries/Comparator#input_n), as my understanding is that it is not feasible:
![image](https://github.com/user-attachments/assets/a4ad749a-39fa-428c-bfb6-c8c6fb7721fa)

My understanding is that the 1614 is "1-series 'plus'" - but that is maybe wrong? 
Re: https://github.com/SpenceKonde/AVR-Guidance/blob/master/AVRFamilies_And_Compatibility/ModernAVRs.md

It is also possible my difficulties have been due to me confusing DACREF with DAC, ref. point 2 in https://github.com/SpenceKonde/megaTinyCore/discussions/1155#discussioncomment-11066385 - which I haven't gotten around to testing yet. However, the code snippet provided there by @MX682X seems to connect dacref to input_n, which seems a bit confusing, I expected the code to indicate this as DAC0 in some way. 

Schematic snippet of my current prototype, where I instead of using internal DAC takes the reference voltage from an external voltage divider into PA6:
![image](https://github.com/user-attachments/assets/b147b441-d298-40bd-9777-a5ef4834235d)

The "Detect" signal is the blue trace in the oscilloscope photos [here](https://github.com/SpenceKonde/megaTinyCore/discussions/1155#discussioncomment-11052972). I was initially doing digital reading on PA2, but that could only detect edges at lower voltage levels. In my application I need to do edge detection close to Vcc. 

The voltage divider is a feasible solution, but it would have been much more efficient and flexible to use the internal DAC to set up that reference.

**Comment by ArnieO** [comment]
I received help in a [discussion thread](https://github.com/SpenceKonde/megaTinyCore/discussions/1155), so the issue is solved.
