### ISSUE TITLE
TLS certificat expired 

### ISSUE THREAD

**Issue by bodtx** [SpenceKonde/megaTinyCore#1157]
Installation failed for board with this source
https://drazzy.com/package_drazzy.com_index.json

the TLS certificat as ended on october 22th 2024

**Comment by hmeijdam** [comment]
You can try using https://github.com/SpenceKonde/megaTinyCore/issues/1059#issuecomment-1950286469

That worked fine last time when the certificate expired.

**Comment by bodtx** [comment]
yes it works thx
I've found also a workaround by downloading the json file and serve it on my machine with

`python -m SimpleHTTPServer 8000`

then I've rewrite the url in boardmanager to point at my localhost server
