### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by concon** [SpenceKonde/megaTinyCore#116]
hi, I get this error when reinstalling.

"Skipping contributed index file C:\Users\lcagl\AppData\Local\Arduino15\package_drazzy.com_index.json, parsing error occured:"

**Comment by Kadah** [comment]
The full error:

```
Skipping contributed index file [...]\AppData\Local\Arduino15\package_drazzy.com_index.json, parsing error occured:
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 2, column: 15])
 at [Source: (FileInputStream); line: 1134, column: 6453]
 at [Source: (FileInputStream); line: 1133, column: 1] (through reference chain: com.fasterxml.jackson.module.mrbean.generated.cc.arduino.contributions.packages.ContributionsIndex["packages"])
```

**Comment by SpenceKonde** [comment]
Will fix later today, looks like I messed up the board manager json

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by SpenceKonde** [comment]
fixed now. Reload board manager and it will work.
