### ISSUE TITLE
Current master branch doesn't compile

### ISSUE THREAD

**Issue by jvasileff** [SpenceKonde/megaTinyCore#1168]
The master branch fails to compile due to an incomplete comment in `core_devices.h` added in ff882057402e7:

https://github.com/SpenceKonde/megaTinyCore/blob/f0e59764d741bdff09b670be0d055b5c728b4788/megaavr/cores/megatinycore/core_devices.h#L734

**Comment by hmeijdam** [comment]
I get the same error.

As a workaround I reverted these two changes in my Github Desktop copy of the current master branch, and now I can compile again. Maybe give that a try also.

![image](https://github.com/user-attachments/assets/2880e36b-bc3a-4196-a722-420523f6f941)

**Comment by jvasileff** [comment]
@hmeijdam thanks, yeah, the fix is to either remove line 734 of `core_devices.h` or revert commit ff8820574
