### ISSUE TITLE
Feature Request: Add build-time support for setting mTC specific Tools menu options

### ISSUE THREAD

**Issue by EclipseBoom** [SpenceKonde/megaTinyCore#1180]
Please add (or explain) how to set Tools menu options such as chip, bod, printf, startup time, PWM etc. options in the user's code overriding the Tools menu.  This can avoid accidentally having those menu options reset/changed/wrong in the GUI when starting a new sketch or changing from one board family etc.

i.e. these build-time options:
`FQBN: megaTinyCore:megaavr:atxy6:chip=1626,clock=8extclock,startuptime=32,bodmode=ensampslow,PWMmux=default
`
I'm thinking something like:

```
#pragma megaavr:atxy6
#pragma chip=1626
#pragma clock=8ext
#pragma PWMmux=default
```

That can be placed at the top of the main sketch file to force the build options and override the GUI menu choices.

a `#pragma burn_bootloader=yes` would be nice as well to ensure that the CPU fuses are always set properly

This is helpful if, for example, you are developing with several identical physical units and want to make sure they are always identically configured when a code update is applied or you want to create another unit after some time and want to make sure it is identical to the earlier ones which might have been programmed months or years beforehand.  Or if you are working on several sketches of the same chip family which are different and use different options.

**Comment by SpenceKonde** [comment]
There's no way to do that provided by the Arduino API. I'd LOVE that feature, don't even get me started, but it's not possible. 

It needs those defines before it starts reading any of your code. >.<
