### ISSUE TITLE
How to burn fuses without without bootloader?

### ISSUE THREAD

**Issue by whmountains** [SpenceKonde/megaTinyCore#119]
I'd rather not use a bootloader, as it just takes up flash space.  But I don't see any way to set fuses without burning a bootloader.  Can I just "burn bootloader" and then promptly erase it using "upload using programmer", or will that make the code not work for some reason?

Thanks!

**Comment by SpenceKonde** [comment]
Use the non-optiboot board option and do "burn bootloader" - for board
definitions without a bootloader, this does exactly what you want - it just
sets fuses (it may also upload a dummy bootloader- I forget if I worked
around that, and am answering from phone so cant easily check - but if it
does this is erased when a sketch is uploaded). There is only an actual
bootloader for the optiboot board definitions (the ones with (optiboot)
after them - if you dont have that option, you're using 1.0.6 or earlier,
which doesnt have optiboot at all. And in that case you should not update
until 1.1.2 is pushed out tonight, as 1.1.1 has a bad bu

Note that, unlike classic AVRs, you *cannot* "burn bootloader" with an
optiboot board definition and then "upload using programmer" to erase the
bootloader and replace with sketch.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com
