### ISSUE TITLE
has_updi switch in avrdude.con

### ISSUE THREAD

**Issue by EclipseBoom** [SpenceKonde/megaTinyCore#125]
At line 15213 in avrdude.conf "has_updi" is commented out for the .avr8x parts

This prevents UPDI programming of this family tree of parts.

**Comment by SpenceKonde** [comment]
Interesting that this is causing problems for you, as I program them over UPDI all the time without issue. What programmer are you using?

**Comment by EclipseBoom** [comment]
Using the microUPDI programmer from MCUDude

**Comment by SpenceKonde** [comment]
please reopen if the changes in the github version don't solve the problem. I am still waiting on my pro micro clones to be able to use my microUPDI programmers.
