### ISSUE TITLE
Disable DAC output -> File not found

### ISSUE THREAD

**Issue by LordJakson** [SpenceKonde/megaTinyCore#141]
Hi
I just installed the megaTinyCore the first time.

I noticed if I disable the DAC output in the Arduino/Tools Menu the compiler print out a Error:

`avr-g++: error: {build.dacvref}: No such file or directory`

Is this normal or did I something wrong?

Arduino 1.8.10, megaTinyCore 1.1.5

**Comment by SpenceKonde** [comment]
Thanks, that would be a bug

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by SpenceKonde** [comment]
Was broken in 14-pin non-optiboot board def (and menu option was missing for 20-pin part optiboot def).
