### ISSUE TITLE
Why do we use TCB for millis!?

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#15]
We have other timers which look less useful. 

There's even an RTC timer. Maybe we should use that?

**Comment by SpenceKonde** [comment]
Okay, the RTC is a non-starter. But why not use timer D for millis?

**Comment by freemovers** [comment]
I was wondering the same thing. TCB is currently used by the Nano. The ATMEGA4809 does not have a TCD, and I was thinking of using that for servo's. I have been using the RTC for some timed interrupts since it is not used anywhere else, using it for millis could be done with the PIT?

**Comment by SpenceKonde** [comment]
#16
