### ISSUE TITLE
Push PWM Frequency To The Maximum

### ISSUE THREAD

**Issue by xbow147** [SpenceKonde/megaTinyCore#152]
Hello, I've been tying for some time now to get a high frequency 8-bit pwm signal (at least 62 khz) on PA3 using attiny212 and couldn't get it to work.. I've tried to disable split mode but for some reason I did not get any pwm at all, if anyone can help with changing the timer prescaler and  disabling split mode that will be great, thank you in advance !

**Comment by SpenceKonde** [comment]
I have added a guide on taking over TCA0. Your example is covered. 

https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/TakingOverTCA0.md
