### ISSUE TITLE
settings millis()/micros() is unclear for me

### ISSUE THREAD

**Issue by avandalen** [SpenceKonde/megaTinyCore#154]
Hi Spence,
The setting millis()/micros () is a long complicated story. To keep it simple, just tell what to do for compatibility, so that old sketches will still work.
With enabled (default), I got this message:
#error "No millis timer selected, but not disabled - can't happen!".
With set to disabled, old sketches go well. So maybe set disabled as default?
greetings from Albert
stay healthy..

**Comment by SpenceKonde** [comment]
Unoh, what board were you using? And is that with 1.1.7?

**Comment by SpenceKonde** [comment]
If you are getting that with default on 1.1.7 that is a critical bug in the core which requires an immediate fix and new release.

**Comment by SpenceKonde** [comment]
Issue fixed, rolling 1.1.8

**Comment by SpenceKonde** [comment]
A #endif was on the wrong side of the #else that reports invalid timer selection

**Comment by SpenceKonde** [comment]
Sorry about that.... 1.1.8 is now available for manual and board manager installation.

**Comment by avandalen** [comment]
thank you very much
