### ISSUE TITLE
Support for `EEPROM` constant `EECR`

### ISSUE THREAD

**Issue by PRosenb** [SpenceKonde/megaTinyCore#156]
Hi Spence,
In the library [EEPROMWearLevel](https://github.com/PRosenb/EEPROMWearLevel/) I use the `EEPROM` related constants `EECR`, `EEDR`, `EEAR`, `EEPM0`, `EEPM1`, `EERIE` and `EEMPE`, `EEPE` in [programZeroBitsToZero()](https://github.com/PRosenb/EEPROMWearLevel/blob/d2083bead12ecd09adf4fb2c76964c4bcdea3f38/EEPROMWearLevel.cpp#L399) and [clearByteToOnes()](https://github.com/PRosenb/EEPROMWearLevel/blob/d2083bead12ecd09adf4fb2c76964c4bcdea3f38/EEPROMWearLevel.cpp#L447) in order to prevent wear of the `EEPROM`. Would it be possible to add these contants to `megaTinyCore` so that this functionality can also be used?
Thanks for considering.

**Comment by SpenceKonde** [comment]
Those aren't constants. Those are hardware registers. They don't exist on the megaavr parts. The procedure for writing to EEPROM is different (also easier - I was sort of shocked, *how* easy, to be honest...)

There is a PR coming to your library to support the megaavr parts.
