### ISSUE TITLE
Expected ')' before '*' token

### ISSUE THREAD

**Issue by Merlin04** [SpenceKonde/megaTinyCore#166]
I have this code in my program to configure interrupts on pins:

```c++
PORTA.PIN4CTRL |= 0b00000101;
PORTA.PIN6CTRL |= 0b00000101;
PORTA.PIN7CTRL |= 0b00000101;
```

When I try to compile it, I get this error on each of the three lines:

> error: expected ')' before '*' token
>  PORTA.PIN7CTRL |= 0b00000101;
>  ^

When I remove the code, the sketch compiles properly. I've set chip to ATtiny3216.

**Comment by Merlin04** [comment]
Moving the code to inside a function fixed the error, but I'm not sure why.

**Comment by SpenceKonde** [comment]
You can't put code outside of a function - not legal C. The errors are often not particularly useful either, as you saw.
