### ISSUE TITLE
Attiny_412_bug

### ISSUE THREAD

**Issue by CommonGrounds** [SpenceKonde/megaTinyCore#169]
In Arduino.h on  **line:59**  you have

#define EXTERNAL    ADC_REFSEL_VREFA_gc

Attiny_412 doesn't have External reference

**Comment by SpenceKonde** [comment]
Argh, I forgot about that exception. 

Funny, I let that slip in, and it gets called out within days. 

Nobody noticed when it wasn't defined on devices that did have it (which was the case prior to 1.1.10)!
