### ISSUE TITLE
Support for analogReadResolution()

### ISSUE THREAD

**Issue by DrMarkEy** [SpenceKonde/megaTinyCore#178]
It would be nice to be able to set the resolution of the analogRead() function.

**Comment by SpenceKonde** [comment]
Implemented by 700bc6b1c51762ac31ac8cb0237a91a0e5b06ba7

Thanks for reporting this - I thought I'd implemented it. 

Note that this is slightly different from what the SAM cores do; only values directly supported by the hardware are valid options - 8 or 10; the function returns a boolean - true if the option supplied was valid (this is meant as a debugging aid). Calling it with an invalid value will set the resolution to the default (10). Future versions will support higher resolutions via oversampling and decimation per Microchip app notes, see #181
