### ISSUE TITLE
Correct tinyAVR x04, x07 pinout diagrams

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#209]
These parts do not have an alternate set of pins for TWI/I2C - only the 1-series parts have that. The SCL/SDA pin labels should be removed from the pinout charts; this was previously done for the x06, but I'd neglected to check whether other parts also needed this treatment.

**Comment by freemovers** [comment]
Removed the alternative pin location on ATtiny_x07.gif and ATtiny_x04.gif

**Comment by SpenceKonde** [comment]
Damn that was fast!

**Comment by SpenceKonde** [comment]
Thanks!
