### ISSUE TITLE
Issue: SDA & SCL redefinition error in x07 variants

### ISSUE THREAD

**Issue by Keanan-prg** [SpenceKonde/megaTinyCore#210]
When using the 1607 or 807 variants, the compiler error below appears. I'm using the 2.0.5 megaTinyCore.

`
Arduino: 1.8.13 (Windows 10), Board: "ATtiny3217/1617/1607/817/807/417, ATtiny1607, 8 MHz, 1.8V (5 MHz or less), Disabled, Disabled, EEPROM retained, Enabled (default timer), Closer to 3v"

In file included from C:\Users\Keanan\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.0.5\cores\arduino/UART.h:28:0,

                 from C:\Users\Keanan\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.0.5\cores\arduino/Arduino.h:314,

                 from sketch\digital_potentiometer.ino.cpp:1:

C:\Users\Keanan\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.0.5\variants\txy7/pins_arduino.h:71:22: error: redefinition of 'const uint8_t SDA'

 static const uint8_t SDA = PIN_WIRE_SDA;

                      ^~~

C:\Users\Keanan\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.0.5\variants\txy7/pins_arduino.h:64:22: note: 'const uint8_t SDA' previously defined here

 static const uint8_t SDA = PIN_WIRE_SDA;

                      ^~~

C:\Users\Keanan\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.0.5\variants\txy7/pins_arduino.h:72:22: error: redefinition of 'const uint8_t SCL'

 static const uint8_t SCL = PIN_WIRE_SCL;

                      ^~~

C:\Users\Keanan\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.0.5\variants\txy7/pins_arduino.h:65:22: note: 'const uint8_t SCL' previously defined here

 static const uint8_t SCL = PIN_WIRE_SCL;

                      ^~~

exit status 1

Error compiling for board ATtiny3217/1617/1607/817/807/417.
`

**Comment by SpenceKonde** [comment]
Fixed by f44a22c07d2b5e9220340d16692820a062f49735
