### ISSUE TITLE
Add Servo library

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#23]
We need a megaAVR compatible implementation of Servo.h. See also #16 regarding where to use what timer.

**Comment by SpenceKonde** [comment]
As for what timer - we should use TCB1 if it's available, otherwise TCB0 (and lose Tone)

**Comment by freemovers** [comment]
Looks like the servo library is already updated for the MEGAAVR (but not standard in the MEGAAVR core):
https://github.com/arduino-libraries/Servo/tree/master/src/megaavr

**Comment by SpenceKonde** [comment]
Then we need to pull in a copy of it and strip out non-megaavr stuff and put it into the libraries folder, as it needs to be adjusted to work on tiny

**Comment by SpenceKonde** [comment]
I threw the servo library linked above in, and set it up to use the timers I said it would use. It should now work, assuming the original library worked.
