### ISSUE TITLE
Add methods that were added to Adafruit_NeoPixel since it was forked to make tinyNeoPixel

### ISSUE THREAD

**Issue by intakenick** [SpenceKonde/megaTinyCore#231]
Are there any plans to implement the remaining missing functions in the neopixel library like ColorHSV or fill()?

**Comment by SpenceKonde** [comment]
"missing functions"? I think you mean "new functions" (er, technically they're "methods", I believe)  - they were added to the adafruit library after tinyNeoPixel was forked from it, and I was entirely unaware of their existence.

The methods that operate on the pixels themselves are identical, adding these will be trivial.

**Comment by intakenick** [comment]
thanks for the response and good callout, "new methods" is what I should have said! I figured as much. I'll take a crack at adding them in and will circle back if I'm successful. Thanks for all of your hard work!

**Comment by SpenceKonde** [comment]
Hmm, they've added more than just those too....

**Comment by SpenceKonde** [comment]
In github version now. (along with untested support for overclocked parts, pulled from DxCore)
