### ISSUE TITLE
Fix some problem with curiosity or curiosity nano option?

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#232]
https://github.com/SpenceKonde/megaTinyCore/pull/229

Apparently there's something wrong with one of the programmers and/or two of the programmers.txt options are redundant (in the latter case, name of programmer that remains should be amended to clarify. Can someone explain the varieties of alphabet soup featured in Microchip's programmer of the month club?

What I'd *love* is a table with the letters, what it stands for, what products it's part of, and what is needed to tell avrdude to use it...

**Comment by WestfW** [comment]
Redundant.  The "nEDBG" "programmer" got left in programmers.txt, but I didn't add the "protocool" to avrdude.conf.
The new "programmer" that works is "Microchip Curiosity Nano", invoking "curiosity_updi"

EDBG:   used on "Xplained Pro" boards.  Debugger/Programmer running on some sort of AVR32 chip.
mEDBG:  used on "Xplained Mini" boards (and Arduino Zero.)   Runs on ATmega32u4.
nEDGB: used on the "Curiosity Nano" boards.   Runs on some SAMD chip.

(I think they all support essentially the same JTAG-to-UPDI protocol, at least with appropriately updated firmware.  mEDBG is allegedly slow.)
