### ISSUE TITLE
Pinout diagrams

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#24]
This is @mcudude's department, but I'm going to need his help here. Of course, this is gated by the actual creation of said pinouts!

**Comment by freemovers** [comment]
![pinout](https://user-images.githubusercontent.com/34286173/59815421-60b5f800-92cd-11e9-9610-e4d12caef4eb.gif)
Will this work. Since we no longer have A# it is showing digital, or digital/analog by color. Not sure about the PWM outputs yet ... Any feedback?

**Comment by freemovers** [comment]
Okay, pin#8 next to PB0 should be 9!

**Comment by freemovers** [comment]
Here they are. It is actually not bad since they are all so similar:

![pinout](https://user-images.githubusercontent.com/34286173/59883610-75949900-936a-11e9-83cc-cd2bae331095.gif)

**Comment by MCUdude** [comment]
I become a dad last week, so my time is kinda limited. As for now you only need pinouts for ATtiny 406/806/1606 and ATtiny416/816/1616/3216? Do you want "dedicated" QFN style pinouts too?

And what are the plans on the other tinyAVR-0 and tinyAVR-1 families? These diagrams seems to be the most recent ones.
<img width="456" alt="Skjermbilde 2019-06-20 23 43 31" src="https://user-images.githubusercontent.com/3238730/59883459-76065180-93b5-11e9-8bd1-b662e0c41596.png">
<img width="445" alt="Skjermbilde 2019-06-20 23 43 39" src="https://user-images.githubusercontent.com/3238730/59883461-769ee800-93b5-11e9-81d3-8f25e228c96d.png">

I have development boards for ATtiny416, Attiny1616 and ATtiny104, so I'm able to help out with testing if I have some spare time.

**Comment by SpenceKonde** [comment]
It looks like @freemovers is able to generate pinout images, so you may be off the hook (grats on the kid!)

The x7 image above depicts a package that does not exist - it's only available in qfn. So we need an image based on that. I have a few other thoughts on things to include in the images that I will post a bit later

**Comment by MCUdude** [comment]
> It looks like @freemovers is able to generate pinout images, so you may be off the hook

Yes, they will definitely do the job! The only thing is that it's very hard to figure out what family ATtinyX(X)X6 really is. Oh, I just found out that ATtiny104 as nothing in common with the ATtiny204/404/804/1604 family.

>  (grats on the kid!)

Thank you! I'm pretty sure I will have to prioritize my a little differently, but I still want to be active here on Github. Time will tell, but if I may be a little slow to reply you now know the reason 😉

**Comment by freemovers** [comment]
Here is the QFN version:
![VQFN](https://user-images.githubusercontent.com/34286173/59890584-73d8ce80-9386-11e9-9dc5-9baac1c9fdf6.gif)
I agree that the naming is confusing, but it was more for me to keep track of the differences. It is probably good to make separate pages for the 0-series or 1-series. @SpenceKonde do you want to use the Wiki to make separate pages for each chip? Maybe we can use the Figure MCUdude posted and link each chip it to a page with the pin layout and other specifications (from the spreadsheet).

**Comment by SpenceKonde** [comment]
The wiki? What wiki? 

My plan was to do what was done on ATTinyCore - https://github.com/SpenceKonde/ATTinyCore/tree/master/avr/extras

My thinking was to create extras folder with 8 documentation files in it:
ATtiny_x16.md
ATtiny_x17.md
ATtiny_x14.md
ATtiny_x12.md
ATtiny_x06.md
ATtiny_x07.md
ATtiny_x04.md
ATtiny_x02.md

which would have feature tables and lists of chip-specific caveats. 

We should have a separate pinout image for 0-series and 1-series anyway, since 1-series have DAC, and on the x16 and x17, two additional PWM pins (PC0, PC1). 

x7 image is missing a few connecting lines. 
x2 image is missing TXD, RXD, SCL, SDA markings.

**Comment by SpenceKonde** [comment]
pinout diagrams should go in megaavr/extras (in the repo as binaries)

**Comment by freemovers** [comment]
@SpenceKonde https://github.com/SpenceKonde/megaTinyCore/wiki
Can you be more specific on the connection lines for the x7, looks to me they are all connected but I might miss something there.
For the x2, are TXD, RXD, SCL and SDA only available when alternative PORTMUX is used, and should PORTMUX be a menu option of done through the sketch?
![image](https://user-images.githubusercontent.com/34286173/59968300-6fc6c100-94ec-11e9-9729-290262fd6add.png)

**Comment by SpenceKonde** [comment]
In the pins_arduino for the x2 series, I do specify the alternate portmux options. I dont quite know how they are used elsewhere in the core.

I dont ser a need to add portmux menu options.if someone needs to change it, that's easy enough to do in the sketch. The way the functions on the pins are arranged in general looks like people wont oftwn have cause to change the portmux settings.

**Comment by SpenceKonde** [comment]
Oh! Fantastic! That looks wonderful

The TCD0 PWM pins aren't shown on x16 x17 pinout images, but everything else looks great.

**Comment by freemovers** [comment]
Thanks! I just fixed the PWM for the x16 and x17 as well.

**Comment by MCUdude** [comment]
In the pinout diagrams, wouldn't it be better to call the SPI clock *SCK* instead of *CLK*?

**Comment by SpenceKonde** [comment]
Good catch, yeah the SPI clock is SCK, not CLK

**Comment by freemovers** [comment]
I think CLK slipped in there since the original pinout from the datasheet has EXTCLK (external clock). Updated the diagrams to show SCK now.

**Comment by mechengineermike** [comment]
<img width="2200" height="1800" alt="Image" src="https://github.com/user-attachments/assets/1474e66f-58ce-4a58-875f-3c9227db9371" 20-pin VQFN pinout was missing from collectio
