### ISSUE TITLE
missing 'upload.tool' configuration parameter ?

### ISSUE THREAD

**Issue by ffred** [SpenceKonde/megaTinyCore#245]
it's working again with the 2.1.1 update for my attiny414 board, but got this error with  attiny3216 (same mEDBG from xplained mini) :
`Error while uploading: missing 'upload.tool' configuration parameter`

**Comment by SpenceKonde** [comment]
Oh for fucks sake... here comes 2.1.2

**Comment by ffred** [comment]
sorry... and thank you. :-)

**Comment by ffred** [comment]
'boards manager' of Arduino still didn't see v2.1.2 yet...
will let you know when I test it.
thanks.

**Comment by SpenceKonde** [comment]
It's available now.

**Comment by ffred** [comment]
it's ok !!
thanks a lot.

**Comment by SpenceKonde** [comment]
I suspect, if someone really put their mind to it, they could create a human readable format for storing data like we store in boards.txt, but which is more difficult to maintain....
