### ISSUE TITLE
POR to invoke bootloader?

### ISSUE THREAD

**Issue by iansexton** [SpenceKonde/megaTinyCore#268]
Installed optiboot on a 1614
Power cycling doesn't seem to start the bootloader? 
So, I configured UPDI pin as RESET, used 'standard' arduino reset circuit.
Works perfectly

**Comment by SpenceKonde** [comment]
This should be fixed in the github version (not available in released version yet); issue was #259. Rather nasty bug, I must say...

**Comment by iansexton** [comment]
Great! Not a big deal but your excellent docs are a bit out of sync with reality.
