### ISSUE TITLE
ArduinoIDE Board Manager error

### ISSUE THREAD

**Issue by Targett363** [SpenceKonde/megaTinyCore#287]
Can't get the Board Manager to find the megaTinyCore.
Hoping it's just a typo in the .json.
IDE shows this error message.

```
Skipping contributed index file C:\Users\targe\AppData\Local\Arduino15\package_drazzy.com_index.json, parsing error occured:
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: (FileInputStream); line: 2, column: 2]
```

**Comment by SpenceKonde** [comment]
I cannot reproduce this issue. 
Can you access http://drazzy.com/package_drazzy.com_index.json? 

Is C:\Users\targe\AppData\Local\Arduino15\package_drazzy.com_index.json valid json? It could bre locally caching an http error maybe?

**Comment by Targett363** [comment]
Looks like it’s Sky’s fault!
I’ll be home Monday and using a better internet provider!
![D955DDB6-FCF2-4845-AAC7-4EC3E1BA5B76](https://user-images.githubusercontent.com/18236284/103470278-ba273000-4d68-11eb-8959-1c4fcefabdcc.jpeg)

Thanks so much!

**Comment by SpenceKonde** [comment]
Huh - really wonder why Sky is blocking me :-P

Does it just block everything that's not https, by default?

(note that we will move to https when I finally have time to get azduino.com sorted out)
