### ISSUE TITLE
OSCCFG fuse appears to be wrong

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#29]
It looks like OSCCFG is set to run at 16MHz, but boards.txt specifies FCPU at 20MHz....

**Comment by SpenceKonde** [comment]
Did this only sneak by before because we were using the 4809 fuse file, which was overwriting all the fuses?

**Comment by freemovers** [comment]
I noticed that the timing was off when I was running it on 16MHz (was the original FCPU setting in the boards file). Haven't done any changes to the fuse settings yet, and I was not even aware the clock setting (OSCCFG) was in the boards.txt.

**Comment by SpenceKonde** [comment]
Huh! Interesting. 

Sounds like a bit of testing is in order then.

**Comment by SpenceKonde** [comment]
Should be fixed.....
