### ISSUE TITLE
New UDPI Serial upload

### ISSUE THREAD

**Issue by chipperdoodles** [SpenceKonde/megaTinyCore#294]
Hi! this isn't an issue more of a clarification question, but wasn't sure if there was a better place to post this!

I'm designing a board with the intention of using this core and was excited to see the new option of serial udpi programming. I just wanted to make sure I read the instructions right:

![image](https://user-images.githubusercontent.com/2191837/104335246-7216b480-54b0-11eb-94aa-c89abdcc92cb.png)

Is this the intended way to wire up the resistors for the serial -> udpi uploader? (the usb-uart chip will be on the same board as the 3217 so the values are based on that and not using external serial breakout board).

Thank you so much! I like these new lil avr and all your work on the core has enabled me to mess around with them!

**Comment by SpenceKonde** [comment]
Lose the 470 ohm resistor if you arent going to hook up other programmers -
it's only there to guarantee that an external programmer, even one without
the series resistor, can program it safely. While it doesnt interfere with
programming via just a serial adapter, it's entirely unnecessary.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by chipperdoodles** [comment]
Thank you!  that would help save some space. Really appreciate the response!
