### ISSUE TITLE
Simplify reading ADC

### ISSUE THREAD

**Issue by freemovers** [SpenceKonde/megaTinyCore#30]
https://github.com/SpenceKonde/megaTinyCore/blob/acc780991b663587c3446d73d247bc418c66abc3/megaavr/cores/arduino/wiring_analog.c#L102
ADC.RES results are split and merged before results are returned. Also interrupts are turned off before results are read before ADC.RES is read. Can we just simplify this all with `return ADC.RES`

**Comment by SpenceKonde** [comment]
I *think* this is safe? But I'm not certain. The reason it might not be is if a time-consuming interrupt fired while reading ADC0.RES (between reading the high and low bytes) and the value of ADC0.RES changed during that time. But I can't see how that could happen if the ADC wasn't in freerunning mode, which it isn't here (right?)
