### ISSUE TITLE
I think firmwares folder can be removed

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#31]
That looks like the firmware that goes on the interface chip for 4809 boards, which won't be in use for attiny boards. Stuffing a SAMD microcontroller into a tiny board is contrary to the idea of a small low cost processor.

**Comment by freemovers** [comment]
I was looking at that code when I was cleaning the folder yesterday. I left it there for now to get some more ideas for a programmer. We have https://github.com/ElTangas/jtag2updi solution for the ATMEGA, but I was wondering if this had any other benefits. I agree that using a SAMD adds so much complexity, but it might be based on the Xplained  Pro boards where the same chip is used (so easier to implement?). But on the other hand the WIFI REV 2 uses an ATMEGA again ...
