### ISSUE TITLE
Improve consistency, grammar, etc in boards.txt

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#359]
I received a long list of minor consistency/formatting/etc issues in the boards.txt menus. Mostly are result of my having not meticulously checked that my formatting was consistent between cores, Sometimes it's not even consistent within a core. 

Those issues must be fixed for 2.3.0.

**Comment by SpenceKonde** [comment]
I am of the belief that I have addressed all of these issues in boards.txt. @technoblogy

**Comment by technoblogy** [comment]
Great! Look forward to seeing the next version.
