### ISSUE TITLE
2.3.1 doesn't like 0/1 Series ATtiny__4 (except 1614) using TCB0

### ISSUE THREAD

**Issue by mechatroniks-git** [SpenceKonde/megaTinyCore#394]
v2.9 compiled the a modified version of this [code](https://raw.githubusercontent.com/tetrabiodistributed/PAPRA-PCB/c38be3ee90f81fe9fc7fcec78938d70674fdf67d/firmware/papracode/papracode.ino) just fine.  The modifications didn't change the timer, just disabled serial debug output and some LED so code can fit in 214. (I'm testing a variety of series 0/1 ICs for completeness)

v2.3.1 throws this error
`
C:\Users\xx\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.3.1\cores\megatinycore\Tone.cpp:84:2: error: 'TCB1' was not declared in this scope
 &TCB1;
  ^~~~
C:\Users\xx\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.3.1\cores\megatinycore\Tone.cpp:84:2: note: suggested alternative: 'TCB0'
 &TCB1;
  ^~~~
  TCB0
exit status 1
Error compiling for board 14-pin tinyAVR 0/1/2-series (ATtinyxxy4).
`
![image](https://user-images.githubusercontent.com/57600622/115126526-83c29900-9f84-11eb-9fd7-cf4f4e25f755.png)

**Comment by mechatroniks-git** [comment]
same with the 204,404,804,1604,414,814,. 1614 & 2-series compile OK.

**Comment by SpenceKonde** [comment]
Thanks, this is why we DESPERATELY NEED #306!!!!!
