### ISSUE TITLE
Add An constants back in

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#42]
On reflection, I think removing these will create more problems than it solves. 

It's much simpler here though, since the ADC on the megaAVRs doesn't have differential channels (interesting - they dropped a feature that the classicAVRs had from the megaAVRs - I suspect the reasoning being that hardly anyone used them)

**Comment by freemovers** [comment]
How should we number the A#, have it match the pin# as follows?
![pinoutT1616](https://user-images.githubusercontent.com/34286173/59869292-d2328c80-9347-11e9-9ce7-7493a3469278.gif)

**Comment by SpenceKonde** [comment]
An constants should resolve to the pin with ADC channel n on it, I think - the awkward bit is that AIN0 is on PA0 - the UPDI pin, which isn't available for use.

I am inclined to not put it on the pinout chart, as a way of discouraging people from doing it and encourage using the digital pin numbers.

**Comment by freemovers** [comment]
I will take the analog of the pin chart, so the picture below is for reference to discuss #24, #6 and #44  

![pinoutT1616](https://user-images.githubusercontent.com/34286173/59877104-fe570900-9359-11e9-8055-ab2ef2f3b92b.gif)

When this works I can start creating the pin-outs for the other sizes as well.
