### ISSUE TITLE
attiny402 device signatures. Missing pymcuprog device file and boards.txt entry for existing workaround

### ISSUE THREAD

**Issue by MadGarra** [SpenceKonde/megaTinyCore#540]
Hi, 

I know it is an old issue, and probably no affecting too many users, but just in case you like to take a look at it...

I'm using release 2.4.2, and found two problems when trying to use some old Attiny402 with the worng signature. The first is related with the compillation. Apparently, there is a missing entry in the boards.txt file, 8-pin non-bootloader ###chip section. --> "atxy2.menu.chip.402w.build.attiny" is missing. 
It is correctly included in the optiboot section (atxy2o.menu.chip.402w.build.attiny=402)

*** Compilation traces before modification (only relevant section)
Detecting libraries used...
"C:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\DxCore\\tools\\avr-gcc\\7.3.0-atmel3.6.1-azduino4b/bin/avr-g++" -c -g -Os -w -std=c++17 -fpermissive -Wno-sized-deallocation -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -mrelax -w -x c++ -E -CC -mmcu=attiny -DF_CPU=8000000L -DCLOCK_SOURCE=0 -DARDUINO=10815 -DARDUINO_AVR_ATtiny402 -DARDUINO_ARCH_MEGAAVR "-DMEGATINYCORE=\"2.4.2\"" -DMEGATINYCORE_MAJOR=2UL -DMEGATINYCORE_MINOR=4UL -DMEGATINYCORE_PATCH=2UL -DMEGATINYCORE_RELEASED=1 -DARDUINO_attinyxy2 -DMILLIS_USE_TIMERA0 -DUARTBAUDNA "-IC:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\megaTinyCore\\hardware\\megaavr\\2.4.2\\cores\\megatinycore/api/deprecated" "-IC:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\megaTinyCore\\hardware\\megaavr\\2.4.2\\cores\\megatinycore" "-IC:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\megaTinyCore\\hardware\\megaavr\\2.4.2\\variants\\txy2" "D:\\Projects\\ArduinoBuild\\sketch\\Blink.ino.cpp" -o nul
Error while detecting libraries included by D:\Projects\ArduinoBuild\sketch\Blink.ino.cpp
*** end of trace

After adding atxy2.menu.chip.402w.build.attiny=402 I was able to compile the code without problems

*** Compilation traces after modification
Detecting libraries used...
"C:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\DxCore\\tools\\avr-gcc\\7.3.0-atmel3.6.1-azduino4b/bin/avr-g++" -c -g -Os -w -std=c++17 -fpermissive -Wno-sized-deallocation -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -mrelax -w -x c++ -E -CC -mmcu=attiny402 -DF_CPU=8000000L -DCLOCK_SOURCE=0 -DARDUINO=10815 -DARDUINO_AVR_ATtiny402 -DARDUINO_ARCH_MEGAAVR "-DMEGATINYCORE=\"2.4.2\"" -DMEGATINYCORE_MAJOR=2UL -DMEGATINYCORE_MINOR=4UL -DMEGATINYCORE_PATCH=2UL -DMEGATINYCORE_RELEASED=1 -DARDUINO_attinyxy2 -DMILLIS_USE_TIMERA0 -DUARTBAUDNA "-IC:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\megaTinyCore\\hardware\\megaavr\\2.4.2\\cores\\megatinycore/api/deprecated" "-IC:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\megaTinyCore\\hardware\\megaavr\\2.4.2\\cores\\megatinycore" "-IC:\\Users\\Fernando\\AppData\\Local\\Arduino15\\packages\\megaTinyCore\\hardware\\megaavr\\2.4.2\\variants\\txy2" "D:\\Projects\\ArduinoBuild\\sketch\\Blink.ino.cpp" -o nul
Generating function prototypes...
*** end of trace

The second problem is related with the upload process using UPDI. There is no attiny402w.py file to define wrong signature ATtine402 device. Just creating a copy from existing attiny402.py at ...\hardware\megaavr\2.4.2\tools\libs\pymcuprog\deviceinfo\devices directory, renaming it to attiny402w.py and modifying the last line from...
 
'#device_id': 0x1E9227,
to...

'#device_id': 0x1E9225,

allowed me to upload the code using SerialUPDI programmer (with 4.7K resistor or diode)

I think thats all.

Regards
Fernando

**Comment by SpenceKonde** [comment]
Good catch. I never got any of the bad chip and it also looks like they aren't in the CI rotation either.

**Comment by MadGarra** [comment]
I ordered them on Nov/2019 for “evaluation”, as an alternative to Attiny25/85, but never really used. Now, with the silicon supply problems I was planning to give them a second chance.
	
By the way, if you are interested, I can send you a pair just in case you like to add them to a “Freak” silicon collection :-)

**Comment by MATTERealise** [comment]
I'm head-bashing my way through bringing up a custom CH340 UPDI programming board. It seems like https://github.com/SpenceKonde/megaTinyCore/blob/1203928c7510e8dcc825cc2f8469e960d5efd82e/megaavr/tools/libs/pymcuprog/deviceinfo/devices/attiny402w.py#L83 is still showing the correct (and therefore wrong for this workaround) device ID.
