### ISSUE TITLE
ATtiny1614/ tone() function / unwanted debug information to the Serial console

### ISSUE THREAD

**Issue by 6v6gt-duino** [SpenceKonde/megaTinyCore#550]
Core version megaTinyCore 2,4,2
Arduino IDE 1.8.16
Attiny1614 / No bootloader

This output:

`
2048
1219
0
2048
1219
0
2048
1219
0
`
appears when used with this sample code;

```
const uint8_t buzzer = 0 ;
const uint8_t led = 2 ;

void setup() {
  Serial.begin( 115200 ) ;
  pinMode( buzzer, OUTPUT ) ;
  pinMode( led, OUTPUT ) ;
}

void loop() {
  tone( buzzer , 2048 ) ;
  delay( 1500 ) ;
  noTone( buzzer ) ;
  digitalWrite( led, HIGH ) ;
  delay(500) ;
  digitalWrite( led, LOW ) ;
}
```

**Comment by hmeijdam** [comment]
How do you get the output with this code? I see no Serial.print statement.

**Comment by SpenceKonde** [comment]
Yikes. Thanks. Wonder how long that's been that way...  It's either since July or March of 2021.

**Comment by hmeijdam** [comment]
And I just reproduced same error on a 404 and 416
