### ISSUE TITLE
2.5.1 Bootloader error

### ISSUE THREAD

**Issue by JasXSL** [SpenceKonde/megaTinyCore#569]
* Arduino 1.8.15
* megaTinyCore 2.5.1
* Installed via boards manager.
* Chip: Attiny402

Whenever I try to burn bootloader I just get
```

Error: cannot parse fuse, 'invalid literal for int() with base 0: '0b1100{bootloader.resetpinbits}01''
Error while burning bootloader.

```

**Comment by SpenceKonde** [comment]
Thank you. fixed in 2.5.2, impacted all parts.
