### ISSUE TITLE
Expanded docs to-do list

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#57]
We need a few general documents relating to megaAVR in general, since things people are used to doing on the classic AVRs won't work here. 

Specifically:
* Direct Port Manipulation (DirectPortManipulation.md) 
* Sleep/Power Save - is anything important different here? (PowerSave.md)
* Manual pin interrupts (I'll take this one, as I want to understand this anyway) (ManualPinInterrupts.md)

I think these .md files should be in extras, and linked from the main page

**Comment by freemovers** [comment]
Added the Direct Port Manipulation and the Sleep/Power Save, with RTC example to wake-up from sleep.

**Comment by SpenceKonde** [comment]
Thanks. I expanded the DirectPortManipulation one and linked them in from README.

**Comment by SpenceKonde** [comment]
PinInterrupts is done, with an example.

**Comment by SpenceKonde** [comment]
Also just noticed and corrected error in PowerSave.md (INT32K is the internal ultra-low power oscillator, OSCULP32K, not  an external 32KHz crystal (XOSC32K)).
