### ISSUE TITLE
Mark VREF and async pins in pinout diagrams

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#58]
The pinout diagrams do not include the VREF pin. This is used for EXTERNAL analog reference, which is available on the 1-series parts (except 412/212) only on PA5.

**Comment by SpenceKonde** [comment]
Also need to mark Px2 and Px6 as fully async interrupt pins (meaning you can use RISING and FALLING interrupts to wake the chip from sleep)

**Comment by freemovers** [comment]
Found an error on the x07 pinout as well where is shows PWM for TCD, needs to be deleted.
