### ISSUE TITLE
UPDI w/ Reset on PB4 Not Programming Fuse

### ISSUE THREAD

**Issue by GeorgeIoak** [SpenceKonde/megaTinyCore#588]
On the 2-Series in order to assign alternate RESET on PB4 it's my understanding that you have to configure SYSCFG0 Bits [3:2] to 0x03

When I change the setting under Tools for this option I don't see the fuses settings don't change on the programming line:

`Set fuses: ['2:0x02', '6:0x04', '8:0x00']`

I would expect to see a setting for offset 5 but it's not there.

I tried this on the ATtiny1626

**Comment by SpenceKonde** [comment]
Looks like you're expecting it to set that fuse on every upload. But that fuse is only written when you "burn bootloader"
(Did you miss "Burn bootloader req'd" next to that submenu?  Which fuses are set on all programming via UPDI, and which is only set on bootload is described in the readme, including the reasoning behind the design decisions). 

As SYSCFG0 is an "unsafe" fuse that can brick the chip if set incorrectly, hence it is only modified when you do "burn bootloader"
