### ISSUE TITLE
serialupdi baud rate issue

### ISSUE THREAD

**Issue by specternecter** [SpenceKonde/megaTinyCore#594]
I've been working on using a 2-series ATtiny to control programming and debugging automatically. 

It took me a while to figure out what was going on here but I finally found it. I modified the baud rate in programmers.txt to be 230404 so that I could watch the serial port and this is what I got...

///////////////////////////////////////////////////////////////////////////////////////////////////////////////
000000: Connect (DOWN): 2021-12-29 11:08:24.9249200 +13285267704.9249191
 Device "\??\USB#VID_10C4&PID_EA60#0001#{0100fdd7-be5a-4808-91f5-05002bc60f72}" has been connected to the system

000001: Create (DOWN): 2021-12-29 11:08:43.0307808 +18.1058608
 Process Id: 27288

000003: I/O Request (DOWN): 2021-12-29 11:08:43.0343936 +0.0000320
 IOCTL_SERIAL_SET_QUEUE_SIZE: Set queue size
	· Input 		= 4096
	· Output		= 4096

000004: I/O Request (UP): 2021-12-29 11:08:43.0343968 +0.0000032
 IOCTL: IOCTL_SERIAL_SET_QUEUE_SIZE

000005: I/O Request (DOWN): 2021-12-29 11:08:43.0344096 +0.0000128
 IOCTL: IOCTL_SERIAL_GET_TIMEOUTS

000006: I/O Request (UP): 2021-12-29 11:08:43.0344112 +0.0000016
 IOCTL_SERIAL_GET_TIMEOUTS: Retrieve timeouts
	· Read interval         		= 0
	· Read total multiplier 		= 0
	· Read total constant   		= 0
	· Write total multiplier		= 0
	· Write total constant  		= 0

000007: I/O Request (DOWN): 2021-12-29 11:08:43.0344224 +0.0000112
 IOCTL_SERIAL_SET_TIMEOUTS: Set timeouts
	· Read interval         		= 0
	· Read total multiplier 		= 0
	· Read total constant   		= 1000
	· Write total multiplier		= 0
	· Write total constant  		= 0

000008: I/O Request (UP): 2021-12-29 11:08:43.0344240 +0.0000016
 IOCTL: IOCTL_SERIAL_SET_TIMEOUTS

000009: I/O Request (DOWN): 2021-12-29 11:08:43.0344304 +0.0000064
 IOCTL_SERIAL_SET_WAIT_MASK: Set wait mask
	· Wait Mask		= SERIAL_EV_ERR (0x80)

000010: I/O Request (UP): 2021-12-29 11:08:43.0344320 +0.0000016
 IOCTL: IOCTL_SERIAL_SET_WAIT_MASK

000011: I/O Request (DOWN): 2021-12-29 11:08:43.0344416 +0.0000096
 IOCTL: IOCTL_SERIAL_GET_BAUD_RATE

000012: I/O Request (UP): 2021-12-29 11:08:43.0344416 +0.0000000
 IOCTL_SERIAL_GET_BAUD_RATE: Retrieve Baud Rate
	· Baud Rate		= 230400

000013: I/O Request (DOWN): 2021-12-29 11:08:43.0344448 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_LINE_CONTROL

000014: I/O Request (UP): 2021-12-29 11:08:43.0344464 +0.0000016
 IOCTL_SERIAL_GET_LINE_CONTROL: Retrieve line control
	· Stop bits		= 1
	· Parity   		= No
	· Data bits		= 8

000015: I/O Request (DOWN): 2021-12-29 11:08:43.0344496 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_CHARS

000016: I/O Request (UP): 2021-12-29 11:08:43.0344496 +0.0000000
 IOCTL_SERIAL_GET_CHARS: Retrieve special characters
	· EOF  		= 0
	· Error		= 0
	· Break		= 0
	· Event		= 0
	· XON  		= 0x11
	· XOFF 		= 0x13

000017: I/O Request (DOWN): 2021-12-29 11:08:43.0344528 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_HANDFLOW

000018: I/O Request (UP): 2021-12-29 11:08:43.0344528 +0.0000000
 IOCTL_SERIAL_GET_HANDFLOW: Retrieve handshake information
	· Control lines		= SERIAL_DTR_CONTROL (0x1)
	· Flow control 		= SERIAL_RTS_CONTROL | SERIAL_XOFF_CONTINUE (0x80000040)
	· Xon Limit    		= 32768
	· Xoff Limit   		= 8192

000019: I/O Request (DOWN): 2021-12-29 11:08:43.0344672 +0.0000144
 IOCTL: IOCTL_SERIAL_GET_BAUD_RATE

000020: I/O Request (UP): 2021-12-29 11:08:43.0344688 +0.0000016
 IOCTL_SERIAL_GET_BAUD_RATE: Retrieve Baud Rate
	· Baud Rate		= 230400

000021: I/O Request (DOWN): 2021-12-29 11:08:43.0344720 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_LINE_CONTROL

000022: I/O Request (UP): 2021-12-29 11:08:43.0344720 +0.0000000
 IOCTL_SERIAL_GET_LINE_CONTROL: Retrieve line control
	· Stop bits		= 1
	· Parity   		= No
	· Data bits		= 8

000023: I/O Request (DOWN): 2021-12-29 11:08:43.0344752 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_CHARS

000024: I/O Request (UP): 2021-12-29 11:08:43.0344768 +0.0000016
 IOCTL_SERIAL_GET_CHARS: Retrieve special characters
	· EOF  		= 0
	· Error		= 0
	· Break		= 0
	· Event		= 0
	· XON  		= 0x11
	· XOFF 		= 0x13

000025: I/O Request (DOWN): 2021-12-29 11:08:43.0344784 +0.0000016
 IOCTL: IOCTL_SERIAL_GET_HANDFLOW

000026: I/O Request (UP): 2021-12-29 11:08:43.0344800 +0.0000016
 IOCTL_SERIAL_GET_HANDFLOW: Retrieve handshake information
	· Control lines		= SERIAL_DTR_CONTROL (0x1)
	· Flow control 		= SERIAL_RTS_CONTROL | SERIAL_XOFF_CONTINUE (0x80000040)
	· Xon Limit    		= 32768
	· Xoff Limit   		= 8192

000027: I/O Request (DOWN): 2021-12-29 11:08:43.0344848 +0.0000048
 IOCTL_SERIAL_SET_BAUD_RATE: Retrieve Baud Rate
	· Baud Rate		= 115200

000028: I/O Request (UP): 2021-12-29 11:08:43.0359264 +0.0014416
 IOCTL: IOCTL_SERIAL_SET_BAUD_RATE

000029: I/O Request (DOWN): 2021-12-29 11:08:43.0359792 +0.0000528
 IOCTL_SERIAL_CLR_RTS: Clear RTS

000030: I/O Request (UP): 2021-12-29 11:08:43.0364080 +0.0004288
 IOCTL: IOCTL_SERIAL_CLR_RTS

000031: I/O Request (DOWN): 2021-12-29 11:08:43.0364688 +0.0000608
 IOCTL_SERIAL_CLR_DTR: Clear DTR

000032: I/O Request (UP): 2021-12-29 11:08:43.0368832 +0.0004144
 IOCTL: IOCTL_SERIAL_CLR_DTR

000033: I/O Request (DOWN): 2021-12-29 11:08:43.0369408 +0.0000576
 IOCTL_SERIAL_SET_LINE_CONTROL: Set line control
	· Stop bits		= 2
	· Parity   		= Even
	· Data bits		= 8

000034: I/O Request (UP): 2021-12-29 11:08:43.0374176 +0.0004768
 IOCTL: IOCTL_SERIAL_SET_LINE_CONTROL

000035: I/O Request (DOWN): 2021-12-29 11:08:43.0374560 +0.0000384
 IOCTL_SERIAL_SET_CHARS: Set special characters
	· EOF  		= 0
	· Error		= 0
	· Break		= 0
	· Event		= 0
	· XON  		= 0x11
	· XOFF 		= 0x13

000036: I/O Request (UP): 2021-12-29 11:08:43.0378672 +0.0004112
 IOCTL: IOCTL_SERIAL_SET_CHARS

000037: I/O Request (DOWN): 2021-12-29 11:08:43.0379216 +0.0000544
 IOCTL_SERIAL_SET_HANDFLOW: Set handshake information
	· Control lines		= 0
	· Flow control 		= SERIAL_XOFF_CONTINUE (0x80000000)
	· Xon Limit    		= 32768
	· Xoff Limit   		= 8192

000038: I/O Request (UP): 2021-12-29 11:08:43.0384672 +0.0005456
 IOCTL: IOCTL_SERIAL_SET_HANDFLOW

000039: I/O Request (DOWN): 2021-12-29 11:08:43.0385392 +0.0000720
 IOCTL_SERIAL_PURGE: Purge requests
	· Mask		= SERIAL_PURGE_TXABORT | SERIAL_PURGE_RXABORT | SERIAL_PURGE_TXCLEAR | SERIAL_PURGE_RXCLEAR (0xf)

000040: I/O Request (UP): 2021-12-29 11:08:43.0895904 +0.0510512
 IOCTL: IOCTL_SERIAL_PURGE

000041: Write (DOWN): 2021-12-29 11:08:43.0898032 +0.0002128
 00                                                .

000043: I/O Request (DOWN): 2021-12-29 11:08:43.0898928 +0.0000304
 IOCTL: IOCTL_SERIAL_GET_COMMSTATUS

000044: I/O Request (UP): 2021-12-29 11:08:43.0899072 +0.0000144
 IOCTL_SERIAL_GET_COMMSTATUS: Retrieve COM status
	· Errors            		= 0
	· Hold reasons      		= 0
	· In queue          		= 0
	· Out queue         		= 0
	· EOF received      		= false
	· Wait for immediate		= false

000046: Read (UP): 2021-12-29 11:08:43.0904528 +0.0004928
 00                                                .

000047: Write (DOWN): 2021-12-29 11:08:43.0906512 +0.0001984
 55 c3 08                                          U..

000049: I/O Request (DOWN): 2021-12-29 11:08:43.0908224 +0.0000592
 IOCTL: IOCTL_SERIAL_GET_COMMSTATUS

000050: I/O Request (UP): 2021-12-29 11:08:43.0908240 +0.0000016
 IOCTL_SERIAL_GET_COMMSTATUS: Retrieve COM status
	· Errors            		= 0
	· Hold reasons      		= 0
	· In queue          		= 0
	· Out queue         		= 0
	· EOF received      		= false
	· Wait for immediate		= false

000052: Read (UP): 2021-12-29 11:08:43.0921168 +0.0012512
 55 c3 08                                          U..

000053: Write (DOWN): 2021-12-29 11:08:43.0923408 +0.0002240
 55 c2 06                                          U..

000055: I/O Request (DOWN): 2021-12-29 11:08:43.0925408 +0.0000640
 IOCTL: IOCTL_SERIAL_GET_COMMSTATUS

000056: I/O Request (UP): 2021-12-29 11:08:43.0925440 +0.0000032
 IOCTL_SERIAL_GET_COMMSTATUS: Retrieve COM status
	· Errors            		= 0
	· Hold reasons      		= 0
	· In queue          		= 0
	· Out queue         		= 0
	· EOF received      		= false
	· Wait for immediate		= false

000058: Read (UP): 2021-12-29 11:08:43.0941056 +0.0015456
 55 c2 06                                          U..

000059: Write (DOWN): 2021-12-29 11:08:43.0943456 +0.0002400
 55 80                                             U.

000061: I/O Request (DOWN): 2021-12-29 11:08:43.0945200 +0.0000864
 IOCTL: IOCTL_SERIAL_GET_COMMSTATUS

000062: I/O Request (UP): 2021-12-29 11:08:43.0945216 +0.0000016
 IOCTL_SERIAL_GET_COMMSTATUS: Retrieve COM status
	· Errors            		= 0
	· Hold reasons      		= 0
	· In queue          		= 0
	· Out queue         		= 0
	· EOF received      		= false
	· Wait for immediate		= false

000064: Read (UP): 2021-12-29 11:08:43.0948768 +0.0003056
 55 80                                             U.

000065: I/O Request (DOWN): 2021-12-29 11:08:43.0949472 +0.0000704
 IOCTL: IOCTL_SERIAL_GET_COMMSTATUS

000066: I/O Request (UP): 2021-12-29 11:08:43.0949488 +0.0000016
 IOCTL_SERIAL_GET_COMMSTATUS: Retrieve COM status
	· Errors            		= 0
	· Hold reasons      		= 0
	· In queue          		= 0
	· Out queue         		= 0
	· EOF received      		= false
	· Wait for immediate		= false

000068: Read (UP): 2021-12-29 11:08:43.0958384 +0.0008768
 40                                                @

000069: Write (DOWN): 2021-12-29 11:08:43.0960432 +0.0002048
 55 c2 06                                          U..

000071: I/O Request (DOWN): 2021-12-29 11:08:43.0961808 +0.0000544
 IOCTL: IOCTL_SERIAL_GET_COMMSTATUS

000072: I/O Request (UP): 2021-12-29 11:08:43.0961840 +0.0000032
 IOCTL_SERIAL_GET_COMMSTATUS: Retrieve COM status
	· Errors            		= 0
	· Hold reasons      		= 0
	· In queue          		= 0
	· Out queue         		= 0
	· EOF received      		= false
	· Wait for immediate		= false

000074: Read (UP): 2021-12-29 11:08:43.0970048 +0.0008080
 55 c2 06                                          U..

000075: Write (DOWN): 2021-12-29 11:08:43.0971440 +0.0001392
 55 c9 01                                          U..

000077: I/O Request (DOWN): 2021-12-29 11:08:43.0972768 +0.0000544
 IOCTL: IOCTL_SERIAL_GET_COMMSTATUS

000078: I/O Request (UP): 2021-12-29 11:08:43.0972800 +0.0000032
 IOCTL_SERIAL_GET_COMMSTATUS: Retrieve COM status
	· Errors            		= 0
	· Hold reasons      		= 0
	· In queue          		= 0
	· Out queue         		= 0
	· EOF received      		= false
	· Wait for immediate		= false

000080: Read (UP): 2021-12-29 11:08:43.0980384 +0.0007456
 55 c9 01                                          U..

000081: I/O Request (DOWN): 2021-12-29 11:08:43.0980960 +0.0000576
 IOCTL_SERIAL_SET_TIMEOUTS: Set timeouts
	· Read interval         		= 0
	· Read total multiplier 		= 0
	· Read total constant   		= 1000
	· Write total multiplier		= 0
	· Write total constant  		= 0

000082: I/O Request (UP): 2021-12-29 11:08:43.0980992 +0.0000032
 IOCTL: IOCTL_SERIAL_SET_TIMEOUTS

000083: I/O Request (DOWN): 2021-12-29 11:08:43.0981072 +0.0000080
 IOCTL_SERIAL_SET_WAIT_MASK: Set wait mask
	· Wait Mask		= SERIAL_EV_ERR (0x80)

000084: I/O Request (UP): 2021-12-29 11:08:43.0981088 +0.0000016
 IOCTL: IOCTL_SERIAL_SET_WAIT_MASK

000085: I/O Request (DOWN): 2021-12-29 11:08:43.0981168 +0.0000080
 IOCTL: IOCTL_SERIAL_GET_BAUD_RATE

000086: I/O Request (UP): 2021-12-29 11:08:43.0981184 +0.0000016
 IOCTL_SERIAL_GET_BAUD_RATE: Retrieve Baud Rate
	· Baud Rate		= 115200

000087: I/O Request (DOWN): 2021-12-29 11:08:43.0981216 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_LINE_CONTROL

000088: I/O Request (UP): 2021-12-29 11:08:43.0981216 +0.0000000
 IOCTL_SERIAL_GET_LINE_CONTROL: Retrieve line control
	· Stop bits		= 2
	· Parity   		= Even
	· Data bits		= 8

000089: I/O Request (DOWN): 2021-12-29 11:08:43.0981248 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_CHARS

000090: I/O Request (UP): 2021-12-29 11:08:43.0981264 +0.0000016
 IOCTL_SERIAL_GET_CHARS: Retrieve special characters
	· EOF  		= 0
	· Error		= 0
	· Break		= 0
	· Event		= 0
	· XON  		= 0x11
	· XOFF 		= 0x13

000091: I/O Request (DOWN): 2021-12-29 11:08:43.0981328 +0.0000064
 IOCTL: IOCTL_SERIAL_GET_HANDFLOW

000092: I/O Request (UP): 2021-12-29 11:08:43.0981344 +0.0000016
 IOCTL_SERIAL_GET_HANDFLOW: Retrieve handshake information
	· Control lines		= 0
	· Flow control 		= SERIAL_XOFF_CONTINUE (0x80000000)
	· Xon Limit    		= 32768
	· Xoff Limit   		= 8192

000093: I/O Request (DOWN): 2021-12-29 11:08:43.0981488 +0.0000144
 IOCTL: IOCTL_SERIAL_GET_BAUD_RATE

000094: I/O Request (UP): 2021-12-29 11:08:43.0981504 +0.0000016
 IOCTL_SERIAL_GET_BAUD_RATE: Retrieve Baud Rate
	· Baud Rate		= 115200

000095: I/O Request (DOWN): 2021-12-29 11:08:43.0981536 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_LINE_CONTROL

000096: I/O Request (UP): 2021-12-29 11:08:43.0981536 +0.0000000
 IOCTL_SERIAL_GET_LINE_CONTROL: Retrieve line control
	· Stop bits		= 2
	· Parity   		= Even
	· Data bits		= 8

000097: I/O Request (DOWN): 2021-12-29 11:08:43.0981568 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_CHARS

000098: I/O Request (UP): 2021-12-29 11:08:43.0981584 +0.0000016
 IOCTL_SERIAL_GET_CHARS: Retrieve special characters
	· EOF  		= 0
	· Error		= 0
	· Break		= 0
	· Event		= 0
	· XON  		= 0x11
	· XOFF 		= 0x13

000099: I/O Request (DOWN): 2021-12-29 11:08:43.0981616 +0.0000032
 IOCTL: IOCTL_SERIAL_GET_HANDFLOW

000100: I/O Request (UP): 2021-12-29 11:08:43.0981616 +0.0000000
 IOCTL_SERIAL_GET_HANDFLOW: Retrieve handshake information
	· Control lines		= 0
	· Flow control 		= SERIAL_XOFF_CONTINUE (0x80000000)
	· Xon Limit    		= 32768
	· Xoff Limit   		= 8192

000101: I/O Request (DOWN): 2021-12-29 11:08:43.0981664 +0.0000048
 IOCTL_SERIAL_SET_BAUD_RATE: Retrieve Baud Rate
	· Baud Rate		= 230404

000102: I/O Request (UP): 2021-12-29 11:08:43.0994592 +0.0012928
 IOCTL: IOCTL_SERIAL_SET_BAUD_RATE

000103: I/O Request (DOWN): 2021-12-29 11:08:43.0995008 +0.0000416
 IOCTL_SERIAL_CLR_RTS: Clear RTS

000104: I/O Request (UP): 2021-12-29 11:08:43.0997648 +0.0002640
 IOCTL: IOCTL_SERIAL_CLR_RTS

000105: I/O Request (DOWN): 2021-12-29 11:08:43.0998080 +0.0000432
 IOCTL_SERIAL_CLR_DTR: Clear DTR

000106: I/O Request (UP): 2021-12-29 11:08:43.1000720 +0.0002640
 IOCTL: IOCTL_SERIAL_CLR_DTR

000107: I/O Request (DOWN): 2021-12-29 11:08:43.1001136 +0.0000416
 IOCTL_SERIAL_SET_LINE_CONTROL: Set line control
	· Stop bits		= 2
	· Parity   		= Even
	· Data bits		= 8

000108: I/O Request (UP): 2021-12-29 11:08:43.1003680 +0.0002544
 IOCTL: IOCTL_SERIAL_SET_LINE_CONTROL

000109: I/O Request (DOWN): 2021-12-29 11:08:43.1004112 +0.0000432
 IOCTL_SERIAL_SET_CHARS: Set special characters
	· EOF  		= 0
	· Error		= 0
	· Break		= 0
	· Event		= 0
	· XON  		= 0x11
	· XOFF 		= 0x13

000110: I/O Request (UP): 2021-12-29 11:08:43.1007616 +0.0003504
 IOCTL: IOCTL_SERIAL_SET_CHARS

000111: I/O Request (DOWN): 2021-12-29 11:08:43.1008048 +0.0000432
 IOCTL_SERIAL_SET_HANDFLOW: Set handshake information
	· Control lines		= 0
	· Flow control 		= SERIAL_XOFF_CONTINUE (0x80000000)
	· Xon Limit    		= 32768
	· Xoff Limit   		= 8192

000112: I/O Request (UP): 2021-12-29 11:08:43.1012848 +0.0004800
 IOCTL: IOCTL_SERIAL_SET_HANDFLOW

000113: Write (DOWN): 2021-12-29 11:08:43.1014352 +0.0001504
 55 e6                                             U.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

.... Now it continues from here how it should, but as you can see it ignores the baud rate passed by programmers.txt for the beginning portion. It sets it to 230400 for a second and then runs at 115200 for a while. Even though programmers.txt is set to 230404. Which does happen, but not for a while.

I modified physical.py in serialupdi so that I could manually set it at 230400 by setting manually_passed_baud and setting passthrough to True like this... 

def initialise_serial(self, port, baud):
        """
        Standard serial port initialisation
        :param port: serial port to use
        :param baud: baud rate
        """
        self.logger.info("Opening port '%s' at '%d' baud", port, baud)
        if passthrough == True:
            try:
                self.ser = serial.Serial(None, manually_passed_baud, parity=serial.PARITY_EVEN, timeout=1, stopbits=serial.STOPBITS_TWO) 
                self.ser.port = port
                self.ser.dtr = False
                self.ser.rts = False
                self.ser.open()
            except SerialException:
                self.logger.error("Unable to open serial port '%s'", port)
                raise
        else:
            try:
                self.ser = serial.Serial(None, baud, parity=serial.PARITY_EVEN, timeout=1, stopbits=serial.STOPBITS_TWO)
                self.ser.port = port
                self.ser.dtr = False
                self.ser.rts = False
                self.ser.open()
            except SerialException:
                self.logger.error("Unable to open serial port '%s'", port)
                raise

...which confirms that this setting the port to 115200 is unnecessary. It really appears to be a bug in serialupdi, in which it's not listening to the baud rate sent by programmers.txt until well after it should

**Comment by SpenceKonde** [comment]
The initialization at 115200 baud is intended, I added it. 
230400 baud is pushing the limits of what the chip is capable of at the default UPDI clock speed (IIRC it's out of spec, but seems to work at least under common use cases). It has to start at a lower speed, and then only after it's set the UPDI clock appropriately can it confidently boost the baud rate.
If there are communication problems it will also close and reopen at 300 baud to send a 0x00 to create a break condition, then close and reopen at 115200 to configure the updi clock and then go back to the baud rate the user requested.

**Comment by SpenceKonde** [comment]
SerialUPDI options receive an update 2.5.6. 

However, the behavior about which you complain (note that you have not described how this behavior is a problem) is unchanged. It cannot communicate with all adapters at 230400 baud in it' power-on-reset state (I don't know why it works at all on some!) because it defaults to the minimum clock option for the programming interface (so that it can be programmed over UPDI even when running at 1.8V). To ensure operation at 230400 baud will work, it needs to be increased. Obviously, we can't do this at 230400 baud. I did find some adapters today that would not work at 230400 baud without changing from /4 (4 MHz) to /2 (8 MHz), which are the same adapters that don't work at 460800 baud without changing to /1 (16 MHz).
