### ISSUE TITLE
Pinout images show wrong pins for 32kHz crystal on 20-pin 1-series parts

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#642]
TOSC1 is on PB3, TOSC2 is on PB2. This is shown correctly for all other parts. The 20-pin 1-series parts incorrectly show it on PB2 and PB1

**Comment by SpenceKonde** [comment]
Oh awesome

By the way - are you still selling those ATtiny84 VUSB boards? If so, let me know which pinout you used for the USB (as far as I can tell at least 3 of the possible 6 permutations of the PORTB pins have been used on 84 and 841 boards.  so I can mention your store in the ATTinyCore 2.0.0 docs, and make that the default option for USB pinout (ATTinyCore is getting a MASSIVE overhaul; the next release will include close to 300 micronucleus binaries (support for the 861 and 1634 being added, though I can't seem to make my 861 prototypes work, and the 1634 prototypes were made with the wrong footprint for the QFN and don't work at all (lol.- like a lot of boards I did recently - see below) and nearly 600 optiboot configurations (this has already been done) as well as major refactoring of almost every file (also all done). Tone is busted on some key parts, the optiboot bootloaders for the 828 aren't getting the right build options, and there are some other minor things, but it's coming out damned soon. 

(yeah my last board order was not my best work. In addition to those two non-working micronucleus boards, I left out a decoupling capacitor on one board, another board is up to 4 cut-and-jumped screwups and I spent the whole weekend debugging the "proven and tested" software, and I made the JST-XH 2.54 footprint with 3.0mm pitch instead of 2.54 (though they could be soldered on, albeit awkwardly), since it was only a 4-pin, a panel with 6 designs on is unusable because I didn't check the V-groove box, so it's one great big board, my 3227 breakout board omitted a critical power connection trace.... The only boards that came out perfect were a few general purpose SMD breakout boards that would be almost impossible to screw up, a respin of a my botched 3224 breakout (which needed only one fix), a board for which the key chip hasn't been released yet and appears to have been further delayed, and an LED controller board that's up to **rev F** (Rev. D had a power and ground pin inverted so the chip failed spectacularly the moment power was applied, and Rev. E had the same problem as the Rev. C. and would get trashed by transients that the high efficiency DC-DC converter could put out (made worse by the shitty connectors I was using, which were prone to intermittents that would cause those transients to occur.... I have declared JST-SM to be unfit for any purpose) need extensive circuit protection external to the board. I once burned out 6 Rev C's trying (and failing) to keep the lights running through an event lasting only a few hours.... and  even that needs a rev G because I had to compromise on the circuit protection components due to this fucking chip shortage)

**Comment by freemovers** [comment]
I sold my last 3 ATtiny84a boards this weekend and decided to obsolete the design. There are much better alternatives out there like optiboot. I have a design ready for an ATtiny1616 with serial converter to run optiboot. 
I feel your pain. For some reason in KiCAD 5.99 it didn't catch traces overlapping foot prints, and now in KiCAD 6 I forgot to copy all the back-layers while I was creating a panel. Fortunately that error was caught just before manufacturing since they sent me a note that there were two designs in the panel instead of just one.  I also fried about 30 ATtiny84a chips after I changed to high temp solder paste. I probably didn't bake these long enough! Every chip is precious today!

**Comment by SpenceKonde** [comment]
Any word on this? (planning to get a "critical bugfix" ojt before end of week,  address another stupid error I made in attachInterrupt() - getting the operants to a mov backwards intending prepare a pointer register .Insead it would fail to clear the intflags and cscribble over a random register in tlowest 256 address es;

**Comment by freemovers** [comment]
I will update the 20 pins tonight. The clocks are not in the pinout images I have here, so I started updating these all to make them all look the same. But I will get at least the 20 pins done today.

**Comment by freemovers** [comment]
Is the 1 series missing CLKOUT on PB5 as well?

**Comment by SpenceKonde** [comment]
Thanks. 

Interesting - squinting and looking closely at the images - I think I must have been the one to add the "CLOCK" pins to the 0-series and 1-series pinout images (notice how they aren't perfectly lined up because it was done in MS paint). It looks like the 20-pin 1-series was the only one I['d screwed up. The others have imperfect pixel spacing around things like the "CLOCK label on the legend, but I don't see an 20 or 24 pin parts missing the CLKO pin, and all the 1-series parts that support a 32k crystal do have the tosc pins marked correctly on PB2 and PB3. Convenient of them to use the same pins that are the default serial pins for that right?..... /eyeroll..... (because see, anything at all on those pins other than a crystal and loading caps will keep it from oscillating. They are insanely sensitive. Both the HFXTAL option on DB and upcoming DD-series parts and the 32k xtal everywhere is more sensitive than it was on previous generations. HF xtal because they don't have as much crystal drive strength as classic AVRs, even when set to the maximum, and 32k ones because they're optimized for ultra low power consumption so the amount of power involved is insanely tiny (sub-uW) thus making it very susceptible to interference.
