### ISSUE TITLE
DxCore tools used when compiling for ATtiny1624/6

### ISSUE THREAD

**Issue by HeadBoffin** [SpenceKonde/megaTinyCore#680]
Just a sense check here - as I can get ATtiny1624's & 6's (thank you Mouser & thank you for limiting purchases so we can all get some) I've a OneWire & I2C based project that **only** compiles for Series 2 if the DxCore is installed as well as this (wonderful) BSP.

Is this expected / correct / documented?

If this is unexpected, I'll capture a failed compile and post it here.

**Comment by SpenceKonde** [comment]
Please capture tre failed compile!!!!!!!!!

**Comment by SpenceKonde** [comment]
It is incorrect becavior, totally unexpected and this is the first I have heard aboiut it!

**Comment by SpenceKonde** [comment]
Actually - was either core installled manually? Additional steps are required for manual because of the strange way that board manager vs manial installs happen.

**Comment by SpenceKonde** [comment]
almost three weeks without required information. Cannot resolve without verbose compile log showing failure
