### ISSUE TITLE
millis() on RTC not increasing while asleep in SLEEP_MODE_PWR_DOWN?

### ISSUE THREAD

**Issue by ObviousInRetrospect** [SpenceKonde/megaTinyCore#688]
Maybe user error but I thought millis() was supposed to track time when asleep when on the RTC.

It works normally with:
```
set_sleep_mode(SLEEP_MODE_STANDBY);
```

but not
```
set_sleep_mode(SLEEP_MODE_PWR_DOWN);
```

Given that the only wakeup condition is PIT, the RTC and xosc32 are clearly running in PWR_DOWN. 

# Full code to reproduce:
```
//MUST be run with millis() on RTC
#include <avr/sleep.h>
int8_t PIT_init()
{
	while (RTC.PITSTATUS > 0) { /* Wait for all register to be synchronized */
	}
	RTC.PITCTRLA = RTC_PERIOD_CYC32768_gc /* RTC Clock Cycles 256 */
	               | 1 << RTC_PITEN_bp; /* Enable: enabled */

	RTC.PITINTCTRL = 1 << RTC_PI_bp; /* Periodic Interrupt: enabled */
	return 0;
}

void setup() {
  Serial.swap();
  Serial.begin(115200, SERIAL_8N1);
  Serial.println("Boot");
  PIT_init();

  while (RTC.STATUS > 0) {
    ; /* Wait for all registers to be synchronized */
  }
  	while (RTC.PITSTATUS > 0) { /* Wait for all register to be synchronized */
	}
  Serial.print("RTC.CLKSEL: "); Serial.println(RTC.CLKSEL,2);
  Serial.print("RTC.PITINTCTRL: "); Serial.println(RTC.PITINTCTRL,2);
  Serial.print("RTC.PITCTRLA: "); Serial.println(RTC.PITCTRLA,2);
  Serial.print("CLKCTRL.XOSC32KCTRLA: "); Serial.println(CLKCTRL.XOSC32KCTRLA,2);
  
  pinMode(PIN_PA6,OUTPUT);
  digitalWrite(PIN_PA6,HIGH);
  Serial.println("SetupDone");
  //set_sleep_mode(SLEEP_MODE_STANDBY);
  set_sleep_mode(SLEEP_MODE_PWR_DOWN);
  sleep_enable();
}

bool blink=false;
volatile uint32_t ticks=0;
ISR(RTC_PIT_vect) {
    RTC.PITINTFLAGS =
      RTC_PI_bm; /* Clear interrupt flag by writing '1' (required) */
  blink=!blink;
  digitalWriteFast(PIN_PA6,blink?HIGH:LOW);
  ticks++;
}


void loop() {
  // put your main code here, to run repeatedly:
  Serial.flush();
  sleep_cpu();
  Serial.print("millis(): ");
  Serial.print(millis());
  Serial.print(" ticks: ");
  Serial.println(ticks);
}
```

# Output using SLEEP_MODE_STANDBY:

Boot
RTC.CLKSEL: 10
RTC.PITINTCTRL: 1
RTC.PITCTRLA: 1110001
CLKCTRL.XOSC32KCTRLA: 11
SetupDone
millis(): 500 ticks: 1
millis(): 1500 ticks: 2
millis(): 2500 ticks: 3
millis(): 3500 ticks: 4
millis(): 4500 ticks: 5
millis(): 5500 ticks: 6
millis(): 6500 ticks: 7
millis(): 7500 ticks: 8
millis(): 8500 ticks: 9
millis(): 9500 ticks: 10
millis(): 10500 ticks: 11
millis(): 11500 ticks: 12
millis(): 12500 ticks: 13
millis(): 13500 ticks: 14
millis(): 14500 ticks: 15
millis(): 15500 ticks: 16

# Output using SLEEP_MODE_PWR_DOWN:

Boot
RTC.CLKSEL: 10
RTC.PITINTCTRL: 1
RTC.PITCTRLA: 1110001
CLKCTRL.XOSC32KCTRLA: 11
SetupDone
millis(): 8 ticks: 1
millis(): 10 ticks: 2
millis(): 12 ticks: 3
millis(): 14 ticks: 4
millis(): 16 ticks: 5
millis(): 18 ticks: 6
millis(): 20 ticks: 7
millis(): 22 ticks: 8
millis(): 24 ticks: 9
millis(): 26 ticks: 10
millis(): 28 ticks: 11

**Comment by SpenceKonde** [comment]
That is correct. 

You must set millis to use the RTC (sacrificing micros in the process) in order to it's time) This is an option from the tools menu. 

A future library is in planning and partly written that will switch between the two when the part goes to sleep but (will apply to all modern AVRs) but this is not ready yet.
