### ISSUE TITLE
Problem burning Optiboot on Curiosity Nano ATtiny3217

### ISSUE THREAD

**Issue by technoblogy** [SpenceKonde/megaTinyCore#697]
I'm trying to burn Optiboot on a Curiosity Nano ATtiny3217 board, so I can use the Serial Monitor. I'm using megaTinyCore 2.5.11.

I've set the Board options to:

Board: "Official Microchip Board w/Optiboot"
Board Name: "Curiosity Nano ATtiny3217"
Port: "/dev/cu.usbmodem1412"
Programmer: "Curiosity Nano (nEDBG, debug chip: ATSAMD21E18)"

When I choose Burn Bootloader I get:

````
avrdude: invalid byte value (0b1100{bootloader.resetpinbits}0{bootloader.eesavebit}) specified for immediate mode
avrdude: read from file '0b1100{bootloader.resetpinbits}0{bootloader.eesavebit}' failed
Error while burning bootloader.
````
Am I doing something wrong? Thanks!

**Comment by SpenceKonde** [comment]
Yes? Obviously you are using a core with a critical bug. Namely two
required parameters ised to specify the fuses. Fix is trivial but no new
release plsnned for mosern avrs until attinycore gets the core i have
promised tyem more than 8 months ago (afterwhich I start calling the old
parts "legacy" and remove the enhancement issue tag from attinycore to
focus on the good parts

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by technoblogy** [comment]
Thanks for the reply - it's not a problem.
