### ISSUE TITLE
Readme has broken link

### ISSUE THREAD

**Issue by 74HC14** [SpenceKonde/megaTinyCore#698]
https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/DirectPortManipulation.md
Should be
https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/Ref_DirectPortManipulation.md

**Comment by SpenceKonde** [comment]
Thanks. 

You know tyou could get your name immortalized as a contributor by PRing stuff like that instead of just making an issue.

**Comment by SpenceKonde** [comment]
Fixed.
