### ISSUE TITLE
Round macro bugged

### ISSUE THREAD

**Issue by JasXSL** [SpenceKonde/megaTinyCore#714]
The rounding macro introduced in the commit linked at the bottom has two issues:

A. It doesn't work with expressions. Ex:  `round(5.55*10) -> 50` whereas `round(55.5) -> 55`. I think you meant to use _x rather than x.
B. It's not a rounding function, it's a floor function. The examples above should both be 56, not 55. If you uncomment the lines linked below, the arduino default round is used, and `round(5.55*10)` outputs 56

https://github.com/SpenceKonde/megaTinyCore/blob/d13ee000929bb03f063018045622c2e707b3477f/megaavr/cores/megatinycore/api/Common.h#L62-L64

**Comment by SpenceKonde** [comment]
Yeah, it's got two mistakes in it it's using the x instead of the copy and missing the parens around that plus or minus 0.5. Rather pathetic.
