### ISSUE TITLE
Unable to use in_p:in2 on ATTiny3216

### ISSUE THREAD

**Issue by TechAUmNu** [SpenceKonde/megaTinyCore#721]
Looks like the test in comparator.h is not working correctly. Looks like FLASH_SIZE isn't defined.

https://github.com/SpenceKonde/megaTinyCore/blob/6bed5576d45b27f1851d11d287469e8a13be40f4/megaavr/libraries/Comparator/src/Comparator.h#L40

**Comment by SpenceKonde** [comment]
Yeah that shoul;d be PROGMEM_SIZE <= not FLASH_SIZE <
