### ISSUE TITLE
Suggestions for jtag2updi documentation

### ISSUE THREAD

**Issue by technoblogy** [SpenceKonde/megaTinyCore#74]
I followed your instructions and can confirm that everything works perfectly; I've had Blink running on an ATtiny412, ATtiny414, and ATtiny3216 on a breadboard.

You could usefully mention the following points in the documentation:

- The file jtag2updi.ino is empty; this is intentional.

- jtag2updi.ino works on ATmega328 boards, as documented, but it won't work on ATmega32U4-based boards, such as the Arduino Micro.

- On uploading from the Arduino IDE I get the error:

`avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description`

I assume this can be ignored as everything works anyway.

**Comment by SpenceKonde** [comment]
Thanks for reporting these, I've updated the UPDI programmer page.
