### ISSUE TITLE
Add fix for no panic no major version found to .txt generator

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/megaTinyCore#768]
See #763 

Even though IT IS NOT OUR BUG BUT A REGRESION IN ARDUINIO

**Comment by ObviousInRetrospect** [comment]
#772

**Comment by SpenceKonde** [comment]
manually worked around for 2.6.0

**Comment by SpenceKonde** [comment]
For the time being this will be worked around manually, until the autogeneration scripts are ready to take over.
