### ISSUE TITLE
Variants missing a definition for txy6 and txy7

### ISSUE THREAD

**Issue by hiduino** [SpenceKonde/megaTinyCore#79]
It appears that the txy6 and txy7 variants file pins_arduino.h are missing a definition for NUM_DIGITAL_PINS.

**Comment by SpenceKonde** [comment]
Done. 

Note that, afaik, FastLED doesn't support megaavr devices - though recent versions of the core include their own optimized tinyNeoPixel library - see https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/tinyNeoPixel.md

**Comment by freemovers** [comment]
FYI - There is a FastLED branch called avrmega. I added the pinout for the ATtiny1616 and was able to run clockless LED's (like the APA102). Looks like full support for the other chips will be there soon.
