### ISSUE TITLE
Error in package_drazzy.com_index.json

### ISSUE THREAD

**Issue by skeatz** [SpenceKonde/megaTinyCore#796]
There is an error in the package_drazzy.com_index.json file [extra comma (,) at the end of line 3241], which prevents the file from being loaded correctly. Error is fixed once the extra comma is removed.

**Comment by ArminJo** [comment]
I get the same error:
https://github.com/Arduino-IRremote/Arduino-IRremote/runs/8300778560?check_suite_focus=true

**Comment by surechillDM** [comment]
> There is an error in the package_drazzy.com_index.json file [extra comma (,) at the end of line 3241], which prevents the file from being loaded correctly. Error is fixed once the extra comma is removed.

I am also getting this same error message

**Comment by SpenceKonde** [comment]
How the hell did this happen, how did changes to that repo get made at all

**Comment by ArminJo** [comment]
Nope 😭 
calling http://drazzy.com/package_drazzy.com_index.json in firefox still gives error SyntaxError: JSON.parse: unexpected character at line 3242 column 11 of the JSON data

**Comment by jsormaz** [comment]
I'm still getting this error

Skipping contributed index file C:\Users\jsorm\AppData\Local\Arduino15\package_drazzy.com_index.json, parsing error occured:
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character (']' (code 93)): expected a value
 at [Source: (FileInputStream); line: 3242, column: 12]
 at [Source: (FileInputStream); line: 3242, column: 11] (through reference chain: cc.arduino.contributions.packages.ContributionsIndex["packages"]->java.util.ArrayList[1]->cc.arduino.contributions.packages.ContributedPackage["tools"]->java.util.ArrayList[6]->cc.arduino.contributions.packages.ContributedTool["systems"])
