### ISSUE TITLE
2Mhz missing from menu

### ISSUE THREAD

**Issue by ObviousInRetrospect** [SpenceKonde/megaTinyCore#814]
![image](https://user-images.githubusercontent.com/42229858/190643022-87935271-0d4e-4c64-8b05-16b76dde0f96.png)

**Comment by ObviousInRetrospect** [comment]
(yes I verified it is also the case on 1.x)

**Comment by SpenceKonde** [comment]
Yeah I just noticed this myself, I'm working on it.

**Comment by ObviousInRetrospect** [comment]
fixed it properly

**Comment by ObviousInRetrospect** [comment]
and wrote a tool to simplify this sort of thing in the future

**Comment by SpenceKonde** [comment]
I had already fixed it with a regex by the time that PR came in... x_x
