### ISSUE TITLE
2.6.1 not yet released via boards manager

### ISSUE THREAD

**Issue by ObviousInRetrospect** [SpenceKonde/megaTinyCore#824]
was cut on GitHub 2 days ago ... what still needs to be done if anything?

**Comment by SpenceKonde** [comment]
Oh goddamnit i thought everything was just going really smoothly!

**Comment by SpenceKonde** [comment]
I'd forgotten to push the updated json before manually kicking off a sync on the webserver.

**Comment by SpenceKonde** [comment]
Closing because it is now.
