### ISSUE TITLE
Support external clocks

### ISSUE THREAD

**Issue by MCUdude** [SpenceKonde/megaTinyCore#84]
Are you planning on adding support for external clocks? It really sucks that the new mega-0 and tiny-0/1 don't have a crystal driver. However, it can be run off a driven clock, and since this is configured on boot rather than in the fuse bits, you can't lock yourself out by accidentally selecting some external clock in the tools menu. And, if the external clock isn't present at boot it will automatically pick the internal oscillator instead (based on your fuse settings).

You can see my approach to this [here](https://github.com/MCUdude/MegaCoreX/blob/6480da146e8b87f5772a7bf3616c97eb2c31c907/megaavr/cores/coreX-corefiles/wiring.c#L294-L322). Feel free to copy as much as you want. If you implement it the same way (or have a better approach I can implement) it will be easier to make unified PlatformIO support for our cores.

BTW I figured that there's no real use for `cpu_freq` other than occupying 4 bytes of RAM, so I simply got rid of it.

**Comment by MCUdude** [comment]
The internal baud rate generator is something completely different than on older AVRs. This means that we don't really need "UART friendly" clock such as 18.432 MHz and 14.7456 MHz.

External clocks only make sense to use if the internal one isn't accurate or stable enough.

**Comment by SpenceKonde** [comment]
I do not see a particular demand to change this - hardly anyone using the arduino IDE messes with external clocks. If I get requests from people using the core for it, I will reconsider this.
