### ISSUE TITLE
Upload via optiboot : AVRDUDE command line options error

### ISSUE THREAD

**Issue by WebGH** [SpenceKonde/megaTinyCore#849]
Platform: 
Windows

Versions:
IDE: 1.8.19
MegaTinyCore: 2.6.1

Issue:
If attiny1616 with optiboot is selected in the tools menu; And if the bootloader is successfully flased; An attempt to program via this bootloader ends in an AVRDUDE command error: invalid baudrate: {upload.speed}

I found {upload.speed} in the platforms.txt file in the AttinyCore/hardware/avr/1.5.2 folder.
If I replace the placeholder {upload.speed} simply with "115200" the upload via bootloader works.

So, it seems the placeholder {upload.speed} in this file is not replaced by an actual value, and instead the literal string{upload.speed} is passed to AVRDUDE...

**Comment by SpenceKonde** [comment]
Ah, and this was already fixed for 2.6.2 - what's holding that up is that I can't seem to make half duplex usart whic was supposed to work since sometime in the 2.5.x's work right
