### ISSUE TITLE
JTAG2UPDI always selected when doing "regular" uploads

### ISSUE THREAD

**Issue by MCUdude** [SpenceKonde/megaTinyCore#85]
Some users (like me) don't use the JTAG2UPDI programmer for uploading. I will have to select my programmer from the tools menu and perform a shift+upload (which uses the default avrdude.conf, not the one shipped with this core).

Wouldn't it be better if all users *had* to choose their programmer (JTAG2UPDI, mEDBG etc.) from the programmer's menu like you have to with MegaCoreX? The only downside with this is that 1200bps touch isn't supported. But the JTAG2UPDI doesn't require this anyways.

In the future, when Optiboot is stable and ready, we can have a separate bootloader menu option. When the "Use bootloader" option is selected, the IDE chooses to use the traditional USB to serial upload approach. When "No bootloader" is selected, it uses the programmer specified in the programmers menu.

**Comment by SpenceKonde** [comment]
Agree, this makes sense.

**Comment by SpenceKonde** [comment]
That should do the trick here.
