### ISSUE TITLE
Comparator.cpp:243:36: error: expected ',' or '...' before 'register8_t'

### ISSUE THREAD

**Issue by lerouxb** [SpenceKonde/megaTinyCore#855]
https://github.com/SpenceKonde/megaTinyCore/blob/34e46152b0ca44638cfb6ea42e04c4294a7a6a8a/megaavr/libraries/Comparator/src/Comparator.cpp#L242

Missing comma

**Comment by SpenceKonde** [comment]
Thanks what version is this, 2.6.2?

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by lerouxb** [comment]
2.6.1. Unable to install 2.6.2 - I get a 404 error. I can see the same code in the master branch.

**Comment by hmeijdam** [comment]
This error?
![image](https://user-images.githubusercontent.com/9595465/200176255-2a0417c3-21b0-418d-bc20-c9bf8dd42a53.png)

**Comment by lerouxb** [comment]
Yes sorry exactly that error - I think my brain autocompleted it as a 404 but in reality I don't know more than that.

**Comment by SpenceKonde** [comment]
fixed in 2.6.3
