### ISSUE TITLE
Clock speed documentation suggestion

### ISSUE THREAD

**Issue by technoblogy** [SpenceKonde/megaTinyCore#87]
You say:

> You must burn bootloader after changing between 16/8/4MHz and 20/10/5MHz to apply the changes (ie, changing from 20MHz to 10MHz does not require burning bootloader, changing from 20MHz to 16MHz does).

What about the 1MHz option? Also it would be useful to say what the speed of a new chip will be by default.

**Comment by SpenceKonde** [comment]
1 MHz uses 16MHz base clock frequency - there's no /20 prescaler option.
