### ISSUE TITLE
ClockDiagnose doesn't complie

### ISSUE THREAD

**Issue by doug-gilbert** [SpenceKonde/megaTinyCore#873]
Source looks corrupted. #ifndef on line 1 is unterminated, errormsg not defined ....  This example code needs some love from its author. Errors is several header files as well. Contact me if you need a diff. Using 1.8.19

**Comment by SpenceKonde** [comment]
I think the only problem was just that missing endiff, because I added the code to test for it being megaTinyCore at the very end. The #if's otherwise look right....
