### ISSUE TITLE
Interrupts may not work on certain pins

### ISSUE THREAD

**Issue by MCUdude** [SpenceKonde/megaTinyCore#88]
This is a rather odd one. Since all pins support interrupts, the official code just creates a function pointer array based on the `EXTERNAL_NUM_INTERRUPTS` macro. for the Uno Wifi and Nano every this is set to 48, even though they only have 41 physical IOs. This is because it assumes all ports have 8 pins and we have PORT A-F. This gives us 48 theoretical pins.  I assume it's done like this to make it easy to figure out what function pointer to jump to when a PORT interrupt occurs.

But, this means that the macro `EXTERNAL_NUM_INTERRUPTS` for ATtinyX16, for instance, has to be 20 instead of 18. Even though PB6 and PB7 don't exist, you still have to take them into account. Even though I don't have any ATtinyX16 hardware I'm pretty sure Interrupts on digital pin 12 and 13 (PC2 and PC3) doesn't work.

IMO it's not a very good implementation, because the entire array is initialized even though you only need one interrupt pin. For ATtinyX16 this means 36 bytes of RAM is being occupied for nothing.

**Comment by SpenceKonde** [comment]
Fixed - it needed to be corrected for 20 and 8 pin parts. 

I think the whole attachInterrupt() system in general is an abomination, and advocate handling external interrupts manually and ignoring attachInterrupt() - when it isn't used at all, (I think) the compiler is smart enough to not waste memory on it.
