### ISSUE TITLE
CLKO PB5 enable

### ISSUE THREAD

**Issue by moroz55555** [SpenceKonde/megaTinyCore#959]
Hello
Tell me how to enable CLKO PB5 ?

**Comment by SpenceKonde** [comment]
Uh
```
uint8_t temp = CLKCTRLA.MCLKCTRLA;
temp |= 0x80;
__PROTECTED_WRITE(CLKCTRL_MCLKCTRLA,temp);
````
and then clock out will be enabled. if you know ytou're using internal osc, could even just
```
__PROTECTED_WRITE(CLKCTRL_MCLKCTRLA, 0x80);
```

**Comment by moroz55555** [comment]
compiles only in this form without one underscore:
_PROTECTED_WRITE(CLKCTRL_MCLKCTRLA, 0x80);

**Comment by SpenceKonde** [comment]
Sorry, I went to check how many underscores and got distracted implementing it.

**Comment by SpenceKonde** [comment]
This will be available as a feature of megaTinyCore.h (Though it is truly trivial to implement) from 2.6.8 onwards.
